const delegationTokenTypes = {
    DESCRIBE_DELEGATION_TOKENS: 'DESCRIBE_DELEGATION_TOKENS',
    DESCRIBE_DELEGATION_TOKENS_PENDING: 'DESCRIBE_DELEGATION_TOKENS_PENDING',
    DESCRIBE_DELEGATION_TOKENS_FULFILLED:
        'DESCRIBE_DELEGATION_TOKENS_FULFILLED',
    DESCRIBE_DELEGATION_TOKENS_REJECTED: 'DESCRIBE_DELEGATION_TOKENS_REJECTED',

    CREATE_DELEGATION_TOKEN: 'CREATE_DELEGATION_TOKEN',
    CREATE_DELEGATION_TOKEN_PENDING: 'CREATE_DELEGATION_TOKEN_PENDING',
    CREATE_DELEGATION_TOKEN_FULFILLED: 'CREATE_DELEGATION_TOKEN_FULFILLED',
    CREATE_DELEGATION_TOKEN_REJECTED: 'CREATE_DELEGATION_TOKEN_REJECTED',

    RENEW_DELEGATION_TOKEN: 'RENEW_DELEGATION_TOKEN',
    RENEW_DELEGATION_TOKEN_PENDING: 'RENEW_DELEGATION_TOKEN_PENDING',
    RENEW_DELEGATION_TOKEN_FULFILLED: 'RENEW_DELEGATION_TOKEN_FULFILLED',
    RENEW_DELEGATION_TOKEN_REJECTED: 'RENEW_DELEGATION_TOKEN_REJECTED',

    EXPIRE_DELEGATION_TOKEN: 'EXPIRE_DELEGATION_TOKEN',
    EXPIRE_DELEGATION_TOKEN_PENDING: 'EXPIRE_DELEGATION_TOKEN_PENDING',
    EXPIRE_DELEGATION_TOKEN_FULFILLED: 'EXPIRE_DELEGATION_TOKEN_FULFILLED',
    EXPIRE_DELEGATION_TOKEN_REJECTED: 'EXPIRE_DELEGATION_TOKEN_REJECTED',
};

export default delegationTokenTypes;
