import { PermissionLabel } from '..';

const CLUSTER_DASHBOARD_PERMISSIONS = {
    CLUSTER_DASHBOARD_FEATURE_ENABLED: 'CLUSTER_DASHBOARD_FEATURE_ENABLED',
    VIEW_CLUSTER_DASHBOARD: 'VIEW_CLUSTER_DASHBOARD',
} as const;

const CLUSTER_DASHBOARD_PERMISSIONS_LIST = [
    CLUSTER_DASHBOARD_PERMISSIONS.CLUSTER_DASHBOARD_FEATURE_ENABLED,
    CLUSTER_DASHBOARD_PERMISSIONS.VIEW_CLUSTER_DASHBOARD,
] as const;

const CLUSTER_DASHBOARD_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable Cluster Dashboard Feature',
        permission:
            CLUSTER_DASHBOARD_PERMISSIONS.CLUSTER_DASHBOARD_FEATURE_ENABLED,
    },
    {
        label: 'View Dashboard',
        permission: CLUSTER_DASHBOARD_PERMISSIONS.VIEW_CLUSTER_DASHBOARD,
    },
];

const ClusterDashboardPermissions = {
    CLUSTER_DASHBOARD_PERMISSIONS,
    CLUSTER_DASHBOARD_PERMISSIONS_LIST,
    CLUSTER_DASHBOARD_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { ClusterDashboardPermissions };
