import { PermissionLabel } from '..';

const CONSUMER_GROUP_PERMISSIONS = {
    CONSUMER_GROUP_FEATURE_ENABLED: 'CONSUMER_GROUP_FEATURE_ENABLED',
    DESCRIBE_CONSUMER_GROUPS: 'DESCRIBE_CONSUMER_GROUPS',
    DELETE_CONSUMER_GROUP: 'DELETE_CONSUMER_GROUP',
    REMOVE_CONSUMER_GROUP_MEMBER: 'REMOVE_CONSUMER_GROUP_MEMBER',
} as const;

const CONSUMER_GROUP_PERMISSIONS_LIST = [
    CONSUMER_GROUP_PERMISSIONS.CONSUMER_GROUP_FEATURE_ENABLED,
    CONSUMER_GROUP_PERMISSIONS.DESCRIBE_CONSUMER_GROUPS,
    CONSUMER_GROUP_PERMISSIONS.DELETE_CONSUMER_GROUP,
    CONSUMER_GROUP_PERMISSIONS.REMOVE_CONSUMER_GROUP_MEMBER,
];

const CONSUMER_GROUP_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable Consumer Group Feature',
        permission: CONSUMER_GROUP_PERMISSIONS.CONSUMER_GROUP_FEATURE_ENABLED,
    },
    {
        label: 'Describe Consumer Groups',
        permission: CONSUMER_GROUP_PERMISSIONS.DESCRIBE_CONSUMER_GROUPS,
    },
    {
        label: 'Delete Consumer Group',
        permission: CONSUMER_GROUP_PERMISSIONS.DELETE_CONSUMER_GROUP,
    },
    {
        label: 'Remove Consumer Group Member',
        permission: CONSUMER_GROUP_PERMISSIONS.REMOVE_CONSUMER_GROUP_MEMBER,
    },
];

const ConsumerGroupPermissions = {
    CONSUMER_GROUP_PERMISSIONS,
    CONSUMER_GROUP_PERMISSIONS_LIST,
    CONSUMER_GROUP_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { ConsumerGroupPermissions };
