import { PermissionLabel } from '..';

const DELEGATION_TOKEN_PERMISSIONS = {
    DELEGATION_TOKEN_FEATURE_ENABLED: 'DELEGATION_TOKEN_FEATURE_ENABLED',
    DESCRIBE_DELEGATION_TOKENS: 'DESCRIBE_DELEGATION_TOKENS',
    CREATE_DELEGATION_TOKEN: 'CREATE_DELEGATION_TOKEN',
    EXPIRE_DELEGATION_TOKEN: 'EXPIRE_DELEGATION_TOKEN',
    RENEW_DELEGATION_TOKEN: 'RENEW_DELEGATION_TOKEN',
} as const;

const DELEGATION_TOKEN_PERMISSIONS_LIST = [
    DELEGATION_TOKEN_PERMISSIONS.DELEGATION_TOKEN_FEATURE_ENABLED,
    DELEGATION_TOKEN_PERMISSIONS.DESCRIBE_DELEGATION_TOKENS,
    DELEGATION_TOKEN_PERMISSIONS.CREATE_DELEGATION_TOKEN,
    DELEGATION_TOKEN_PERMISSIONS.EXPIRE_DELEGATION_TOKEN,
    DELEGATION_TOKEN_PERMISSIONS.RENEW_DELEGATION_TOKEN,
] as const;

const DELEGATION_TOKEN_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable Delegation Token Feature',
        permission:
            DELEGATION_TOKEN_PERMISSIONS.DELEGATION_TOKEN_FEATURE_ENABLED,
    },
    {
        label: 'Describe Delegation Tokens',
        permission: DELEGATION_TOKEN_PERMISSIONS.DESCRIBE_DELEGATION_TOKENS,
    },
    {
        label: 'Create Delegation Token',
        permission: DELEGATION_TOKEN_PERMISSIONS.CREATE_DELEGATION_TOKEN,
    },
    {
        label: 'Expire Delegation Token',
        permission: DELEGATION_TOKEN_PERMISSIONS.EXPIRE_DELEGATION_TOKEN,
    },
    {
        label: 'Renew Delegation Token',
        permission: DELEGATION_TOKEN_PERMISSIONS.RENEW_DELEGATION_TOKEN,
    },
];

const DelegationTokenPermissions = {
    DELEGATION_TOKEN_PERMISSIONS,
    DELEGATION_TOKEN_PERMISSIONS_LIST,
    DELEGATION_TOKEN_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { DelegationTokenPermissions };
