import { PermissionLabel } from '..';

const OFFSET_PERMISSIONS = {
    ALTER_CONSUMER_GROUP_OFFSETS: 'ALTER_CONSUMER_GROUP_OFFSETS',
    CLEAR_CONSUMER_GROUP_OFFSETS: 'CLEAR_CONSUMER_GROUP_OFFSETS',
    LIST_CONSUMER_GROUP_OFFSETS: 'LIST_CONSUMER_GROUP_OFFSETS',
    LIST_TOPIC_PARTITION_OFFSETS: 'LIST_TOPIC_PARTITION_OFFSETS',
} as const;

const OFFSET_PERMISSIONS_LIST = [
    OFFSET_PERMISSIONS.ALTER_CONSUMER_GROUP_OFFSETS,
    OFFSET_PERMISSIONS.CLEAR_CONSUMER_GROUP_OFFSETS,
    OFFSET_PERMISSIONS.LIST_CONSUMER_GROUP_OFFSETS,
    OFFSET_PERMISSIONS.LIST_TOPIC_PARTITION_OFFSETS,
] as const;

const OFFSET_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Alter Consumer Group Offsets',
        permission: OFFSET_PERMISSIONS.ALTER_CONSUMER_GROUP_OFFSETS,
    },
    {
        label: 'Clear Consumer Group Offsets',
        permission: OFFSET_PERMISSIONS.CLEAR_CONSUMER_GROUP_OFFSETS,
    },
    {
        label: 'List Consumer Group Offsets',
        permission: OFFSET_PERMISSIONS.LIST_CONSUMER_GROUP_OFFSETS,
    },
    {
        label: 'List Topic Partition Offsets',
        permission: OFFSET_PERMISSIONS.LIST_TOPIC_PARTITION_OFFSETS,
    },
];

const OffsetPermissions = {
    OFFSET_PERMISSIONS,
    OFFSET_PERMISSIONS_LIST,
    OFFSET_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { OffsetPermissions };
