const settingsTypes = {
    GET_PROPERTIES: 'GET_PROPERTIES',
    GET_PROPERTIES_PENDING: 'GET_PROPERTIES_PENDING',
    GET_PROPERTIES_FULFILLED: 'GET_PROPERTIES_FULFILLED',
    GET_PROPERTIES_REJECTED: 'GET_PROPERTIES_REJECTED',

    GET_CONFIGURATION: 'GET_CONFIGURATION',
    GET_CONFIGURATION_PENDING: 'GET_CONFIGURATION_PENDING',
    GET_CONFIGURATION_FULFILLED: 'GET_CONFIGURATION_FULFILLED',
    GET_CONFIGURATION_REJECTED: 'GET_CONFIGURATION_REJECTED',
};

export default settingsTypes;
