import { PermissionLabel } from '..';

const KAFKA_CONNECT_DASHBOARD_PERMISSIONS = {
    KAFKA_CONNECT_DASHBOARD_FEATURE_ENABLED:
        'KAFKA_CONNECT_DASHBOARD_FEATURE_ENABLED',
    VIEW_KAFKA_CONNECT_DASHBOARD: 'VIEW_KAFKA_CONNECT_DASHBOARD',
} as const;

const KAFKA_CONNECT_DASHBOARD_PERMISSIONS_LIST = [
    KAFKA_CONNECT_DASHBOARD_PERMISSIONS.KAFKA_CONNECT_DASHBOARD_FEATURE_ENABLED,
    KAFKA_CONNECT_DASHBOARD_PERMISSIONS.VIEW_KAFKA_CONNECT_DASHBOARD,
] as const;

const KAFKA_CONNECT_DASHBOARD_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] =
    [
        {
            label: 'Enable Kafka Connect Dashboard Feature',
            permission:
                KAFKA_CONNECT_DASHBOARD_PERMISSIONS.KAFKA_CONNECT_DASHBOARD_FEATURE_ENABLED,
        },
        {
            label: 'View Dashboard',
            permission:
                KAFKA_CONNECT_DASHBOARD_PERMISSIONS.VIEW_KAFKA_CONNECT_DASHBOARD,
        },
    ];

const KafkaConnectDashboardPermissions = {
    KAFKA_CONNECT_DASHBOARD_PERMISSIONS,
    KAFKA_CONNECT_DASHBOARD_PERMISSIONS_LIST,
    KAFKA_CONNECT_DASHBOARD_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { KafkaConnectDashboardPermissions };
