CREATE TABLE IF NOT EXISTS server_permissions (
    id BIGINT NOT NULL,

    created_by TEXT,
    updated_by TEXT,
    creation_time BIGINT,
    update_time BIGINT,

    cluster_permissions TEXT,
    kafka_connect_permissions TEXT,
    schema_registry_permissions TEXT,
    ksql_db_permissions TEXT,
    management_permissions TEXT,
    playground_permissions TEXT,

    PRIMARY KEY (id)
);

INSERT INTO server_permissions
(
    id,
    created_by,
    updated_by,
    creation_time,
    update_time,
    cluster_permissions,
    kafka_connect_permissions,
    schema_registry_permissions,
    ksql_db_permissions,
    management_permissions,
    playground_permissions
)
VALUES (
    1,
    'Blazing Schema Initializer',
    'Blazing Schema Initializer',
    0,
    0,
    null,
    null,
    null,
    null,
    'MANAGEMENT_KAFKA_CONNECT_FEATURE_ENABLED;;;MANAGEMENT_DESCRIBE_KAFKA_CONNECTS;;;MANAGEMENT_CREATE_KAFKA_CONNECT;;;MANAGEMENT_TEST_KAFKA_CONNECT_CONNECTIVITY;;;MANAGEMENT_EDIT_KAFKA_CONNECT;;;MANAGEMENT_DELETE_KAFKA_CONNECT;;;MANAGEMENT_DELETE_SCHEMA_REGISTRY;;;MANAGEMENT_EDIT_SCHEMA_REGISTRY;;;MANAGEMENT_TEST_SCHEMA_REGISTRY_CONNECTIVITY;;;MANAGEMENT_CREATE_SCHEMA_REGISTRY;;;MANAGEMENT_DESCRIBE_SCHEMA_REGISTRIES;;;MANAGEMENT_SCHEMA_REGISTRY_FEATURE_ENABLED;;;MANAGEMENT_CLUSTER_FEATURE_ENABLED;;;MANAGEMENT_DESCRIBE_CLUSTERS;;;MANAGEMENT_CREATE_CLUSTER;;;MANAGEMENT_TEST_CLUSTER_CONNECTIVITY;;;MANAGEMENT_EDIT_CLUSTER;;;MANAGEMENT_DELETE_CLUSTER;;;DELETE_GROUP_WITH_USERS;;;DELETE_GROUP;;;EDIT_GROUP;;;CREATE_GROUP;;;DESCRIBE_GROUPS;;;GROUP_FEATURE_ENABLED;;;CREATE_USER;;;EDIT_USER;;;EDIT_USER_PASSWORD;;;EDIT_USER_PASSWORD_WITHOUT_CURRENT;;;DELETE_USER;;;OIDC_PROVIDER_FEATURE_ENABLED;;;DESCRIBE_OIDC_PROVIDERS;;;CREATE_OIDC_PROVIDER;;;TEST_OIDC_PROVIDER_CONFIGURATION;;;EDIT_OIDC_PROVIDER;;;DELETE_OIDC_PROVIDER;;;SERVER_PERMISSIONS_FEATURE_ENABLED;;;DESCRIBE_SERVER_PERMISSIONS;;;EDIT_SERVER_PERMISSIONS;;;DATA_MASKING_FEATURE_ENABLED;;;DESCRIBE_DATA_MASKINGS;;;CREATE_DATA_MASKING;;;EDIT_DATA_MASKING;;;DELETE_DATA_MASKING;;;CREATE_FILE;;;DELETE_FILE;;;AUDIT_FEATURE_ENABLED;;;SEARCH_AUDIT_LOG;;;ALERT_FEATURE_ENABLED;;;MANAGEMENT_KSQLDB_FEATURE_ENABLED;;;MANAGEMENT_DESCRIBE_KSQLDBS;;;MANAGEMENT_CREATE_KSQLDB;;;MANAGEMENT_TEST_KSQLDB_CONNECTIVITY;;;MANAGEMENT_EDIT_KSQLDB;;;MANAGEMENT_DELETE_KSQLDB;;;USER_FEATURE_ENABLED;;;DESCRIBE_USERS;;;MANAGEMENT_EXPORT_CLUSTER;;;MANAGEMENT_IMPORT_CLUSTER;;;MANAGEMENT_EXPORT_KAFKA_CONNECT;;;MANAGEMENT_IMPORT_KAFKA_CONNECT;;;MANAGEMENT_EXPORT_SCHEMA_REGISTRY;;;MANAGEMENT_IMPORT_SCHEMA_REGISTRY;;;IMPORT_USERS;;;EXPORT_USERS;;;IMPORT_GROUPS;;;EXPORT_GROUPS;;;MANAGEMENT_IMPORT_KSQLDB;;;MANAGEMENT_EXPORT_KSQLDB;;;IMPORT_DATA_MASKINGS;;;EXPORT_DATA_MASKINGS',
    'SCHEMAS_CONTENT_FEATURE_ENABLED;;;SCHEMAS_CONTENT_VALIDATE_SCHEMA;;;SCHEMAS_DEFINITION_FEATURE_ENABLED;;;SCHEMAS_DEFINITION_VALIDATE_SCHEMA;;;OPENAPI_CONTENT_FEATURE_ENABLED;;;OPENAPI_CONTENT_VALIDATE_SCHEMA;;;OPENAPI_DEFINITION_FEATURE_ENABLED;;;OPENAPI_DEFINITION_VALIDATE_SCHEMA;;;CONTENT_VALIDATION_FEATURE_ENABLED;;;CONTENT_VALIDATION_VALIDATE_SCHEMA;;;CONTENT_DIFF_FEATURE_ENABLED;;;CONTENT_DIFF_RUN;;;CONVERSIONS_FEATURE_ENABLED;;;CONVERSIONS_RUN'
);