const consumerGroupTypes = {
    GET_ALL_CONSUMER_GROUPS_LISTINGS: 'GET_ALL_CONSUMER_GROUPS_LISTINGS',
    GET_ALL_CONSUMER_GROUPS_LISTINGS_PENDING:
        'GET_ALL_CONSUMER_GROUPS_LISTINGS_PENDING',
    GET_ALL_CONSUMER_GROUPS_LISTINGS_FULFILLED:
        'GET_ALL_CONSUMER_GROUPS_LISTINGS_FULFILLED',
    GET_ALL_CONSUMER_GROUPS_LISTINGS_REJECTED:
        'GET_ALL_CONSUMER_GROUPS_LISTINGS_REJECTED',

    GET_ALL_CONSUMER_GROUPS_DESCRIPTIONS:
        'GET_ALL_CONSUMER_GROUPS_DESCRIPTIONS',
    GET_ALL_CONSUMER_GROUPS_DESCRIPTIONS_PENDING:
        'GET_ALL_CONSUMER_GROUPS_DESCRIPTIONS_PENDING',
    GET_ALL_CONSUMER_GROUPS_DESCRIPTIONS_FULFILLED:
        'GET_ALL_CONSUMER_GROUPS_DESCRIPTIONS_FULFILLED',
    GET_ALL_CONSUMER_GROUPS_DESCRIPTIONS_REJECTED:
        'GET_ALL_CONSUMER_GROUPS_DESCRIPTIONS_REJECTED',

    GET_CONSUMER_GROUP_DESCRIPTION: 'GET_CONSUMER_GROUP_DESCRIPTION',
    GET_CONSUMER_GROUP_DESCRIPTION_PENDING:
        'GET_CONSUMER_GROUP_DESCRIPTION_PENDING',
    GET_CONSUMER_GROUP_DESCRIPTION_FULFILLED:
        'GET_CONSUMER_GROUP_DESCRIPTION_FULFILLED',
    GET_CONSUMER_GROUP_DESCRIPTION_REJECTED:
        'GET_CONSUMER_GROUP_DESCRIPTION_REJECTED',

    DELETE_CONSUMER_GROUP: 'DELETE_CONSUMER_GROUP',
    DELETE_CONSUMER_GROUP_PENDING: 'DELETE_CONSUMER_GROUP_PENDING',
    DELETE_CONSUMER_GROUP_FULFILLED: 'DELETE_CONSUMER_GROUP_FULFILLED',
    DELETE_CONSUMER_GROUP_REJECTED: 'DELETE_CONSUMER_GROUP_REJECTED',

    DELETE_MEMBER: 'DELETE_MEMBER',
    DELETE_MEMBER_PENDING: 'DELETE_MEMBER_PENDING',
    DELETE_MEMBER_FULFILLED: 'DELETE_MEMBER_FULFILLED',
    DELETE_MEMBER_REJECTED: 'DELETE_MEMBER_REJECTED',
};

export default consumerGroupTypes;
