package com.redadani1997.blazingkraft.common.constant;

public class CommonEnvConstants {
    // BLAZING ADMIN
    public static final String BLAZINGKRAFT_ADMIN_EMAIL = "BLAZINGKRAFT_ADMIN_EMAIL";
    public static final String BLAZINGKRAFT_ADMIN_PASSWORD = "BLAZINGKRAFT_ADMIN_PASSWORD";

    // AUDIT
    public static final String BLAZINGKRAFT_AUDIT_LEVEL = "BLAZINGKRAFT_AUDIT_LEVEL";

    // OIDC PROVIDER
    public static final String BLAZINGKRAFT_OIDC_PROVIDER_CODE = "BLAZINGKRAFT_OIDC_PROVIDER_CODE";
    public static final String BLAZINGKRAFT_OIDC_PROVIDER_NAME = "BLAZINGKRAFT_OIDC_PROVIDER_NAME";
    public static final String BLAZINGKRAFT_OIDC_PROVIDER_ISSUER =
            "BLAZINGKRAFT_OIDC_PROVIDER_ISSUER";
    public static final String BLAZINGKRAFT_OIDC_PROVIDER_PKCE_ENABLED =
            "BLAZINGKRAFT_OIDC_PROVIDER_PKCE_ENABLED";
    public static final String BLAZINGKRAFT_OIDC_PROVIDER_PROVIDER_TYPE =
            "BLAZINGKRAFT_OIDC_PROVIDER_PROVIDER_TYPE";
    public static final String BLAZINGKRAFT_OIDC_PROVIDER_CLIENT_ID =
            "BLAZINGKRAFT_OIDC_PROVIDER_CLIENT_ID";
    public static final String BLAZINGKRAFT_OIDC_PROVIDER_CLIENT_SECRET =
            "BLAZINGKRAFT_OIDC_PROVIDER_CLIENT_SECRET";
    public static final String BLAZINGKRAFT_OIDC_PROVIDER_SCOPES =
            "BLAZINGKRAFT_OIDC_PROVIDER_SCOPES";

    // DATABASES
    public static final String BLAZINGKRAFT_DATASOURCE_TYPE = "BLAZINGKRAFT_DATASOURCE_TYPE";

    public static final String BLAZINGKRAFT_DATASOURCE_POSTGRESQL_URL =
            "BLAZINGKRAFT_DATASOURCE_POSTGRESQL_URL";
    public static final String BLAZINGKRAFT_DATASOURCE_POSTGRESQL_USERNAME =
            "BLAZINGKRAFT_DATASOURCE_POSTGRESQL_USERNAME";
    public static final String BLAZINGKRAFT_DATASOURCE_POSTGRESQL_PASSWORD =
            "BLAZINGKRAFT_DATASOURCE_POSTGRESQL_PASSWORD";

    public static final String BLAZINGKRAFT_DATASOURCE_MYSQL_URL =
            "BLAZINGKRAFT_DATASOURCE_MYSQL_URL";
    public static final String BLAZINGKRAFT_DATASOURCE_MYSQL_USERNAME =
            "BLAZINGKRAFT_DATASOURCE_MYSQL_USERNAME";
    public static final String BLAZINGKRAFT_DATASOURCE_MYSQL_PASSWORD =
            "BLAZINGKRAFT_DATASOURCE_MYSQL_PASSWORD";

    public static final String BLAZINGKRAFT_DATASOURCE_MARIADB_URL =
            "BLAZINGKRAFT_DATASOURCE_MARIADB_URL";
    public static final String BLAZINGKRAFT_DATASOURCE_MARIADB_USERNAME =
            "BLAZINGKRAFT_DATASOURCE_MARIADB_USERNAME";
    public static final String BLAZINGKRAFT_DATASOURCE_MARIADB_PASSWORD =
            "BLAZINGKRAFT_DATASOURCE_MARIADB_PASSWORD";

    public static final String BLAZINGKRAFT_DATASOURCE_SQLSERVER_URL =
            "BLAZINGKRAFT_DATASOURCE_SQLSERVER_URL";
    public static final String BLAZINGKRAFT_DATASOURCE_SQLSERVER_USERNAME =
            "BLAZINGKRAFT_DATASOURCE_SQLSERVER_USERNAME";
    public static final String BLAZINGKRAFT_DATASOURCE_SQLSERVER_PASSWORD =
            "BLAZINGKRAFT_DATASOURCE_SQLSERVER_PASSWORD";
}
