const aclTypes = {
    GET_ACL_BINDINGS: 'GET_ACL_BINDINGS',
    GET_ACL_BINDINGS_PENDING: 'GET_ACL_BINDINGS_PENDING',
    GET_ACL_BINDINGS_FULFILLED: 'GET_ACL_BINDINGS_FULFILLED',
    GET_ACL_BINDINGS_REJECTED: 'GET_ACL_BINDINGS_REJECTED',

    CREATE_ACL_BINDING: 'CREATE_ACL_BINDING',
    CREATE_ACL_BINDING_PENDING: 'CREATE_ACL_BINDING_PENDING',
    CREATE_ACL_BINDING_FULFILLED: 'CREATE_ACL_BINDING_FULFILLED',
    CREATE_ACL_BINDING_REJECTED: 'CREATE_ACL_BINDING_REJECTED',

    DELETE_ACL_BINDING: 'DELETE_ACL_BINDING',
    DELETE_ACL_BINDING_PENDING: 'DELETE_ACL_BINDING_PENDING',
    DELETE_ACL_BINDING_FULFILLED: 'DELETE_ACL_BINDING_FULFILLED',
    DELETE_ACL_BINDING_REJECTED: 'DELETE_ACL_BINDING_REJECTED',
};

export default aclTypes;
