const offsetTypes = {
    ALTER_CONSUMER_GROUP_OFFSETS: 'ALTER_CONSUMER_GROUP_OFFSETS',
    ALTER_CONSUMER_GROUP_OFFSETS_PENDING:
        'ALTER_CONSUMER_GROUP_OFFSETS_PENDING',
    ALTER_CONSUMER_GROUP_OFFSETS_FULFILLED:
        'ALTER_CONSUMER_GROUP_OFFSETS_FULFILLED',
    ALTER_CONSUMER_GROUP_OFFSETS_REJECTED:
        'ALTER_CONSUMER_GROUP_OFFSETS_REJECTED',

    LIST_CONSUMER_GROUP_OFFSETS: 'LIST_CONSUMER_GROUP_OFFSETS',
    LIST_CONSUMER_GROUP_OFFSETS_PENDING: 'LIST_CONSUMER_GROUP_OFFSETS_PENDING',
    LIST_CONSUMER_GROUP_OFFSETS_FULFILLED:
        'LIST_CONSUMER_GROUP_OFFSETS_FULFILLED',
    LIST_CONSUMER_GROUP_OFFSETS_REJECTED:
        'LIST_CONSUMER_GROUP_OFFSETS_REJECTED',

    DELETE_CONSUMER_GROUP_OFFSETS: 'DELETE_CONSUMER_GROUP_OFFSETS',
    DELETE_CONSUMER_GROUP_OFFSETS_PENDING:
        'DELETE_CONSUMER_GROUP_OFFSETS_PENDING',
    DELETE_CONSUMER_GROUP_OFFSETS_FULFILLED:
        'DELETE_CONSUMER_GROUP_OFFSETS_FULFILLED',
    DELETE_CONSUMER_GROUP_OFFSETS_REJECTED:
        'DELETE_CONSUMER_GROUP_OFFSETS_REJECTED',

    LIST_TOPIC_PARTITIONS_OFFSETS: 'LIST_TOPIC_PARTITIONS_OFFSETS',
    LIST_TOPIC_PARTITIONS_OFFSETS_PENDING:
        'LIST_TOPIC_PARTITIONS_OFFSETS_PENDING',
    LIST_TOPIC_PARTITIONS_OFFSETS_FULFILLED:
        'LIST_TOPIC_PARTITIONS_OFFSETS_FULFILLED',
    LIST_TOPIC_PARTITIONS_OFFSETS_REJECTED:
        'LIST_TOPIC_PARTITIONS_OFFSETS_REJECTED',

    LIST_CONSUMER_GROUP_EARLIEST_TOPIC_PARTITIONS_OFFSETS:
        'LIST_CONSUMER_GROUP_EARLIEST_TOPIC_PARTITIONS_OFFSETS',
    LIST_CONSUMER_GROUP_EARLIEST_TOPIC_PARTITIONS_OFFSETS_PENDING:
        'LIST_CONSUMER_GROUP_EARLIEST_TOPIC_PARTITIONS_OFFSETS_PENDING',
    LIST_CONSUMER_GROUP_EARLIEST_TOPIC_PARTITIONS_OFFSETS_FULFILLED:
        'LIST_CONSUMER_GROUP_EARLIEST_TOPIC_PARTITIONS_OFFSETS_FULFILLED',
    LIST_CONSUMER_GROUP_EARLIEST_TOPIC_PARTITIONS_OFFSETS_REJECTED:
        'LIST_CONSUMER_GROUP_EARLIEST_TOPIC_PARTITIONS_OFFSETS_REJECTED',

    LIST_CONSUMER_GROUP_LATEST_TOPIC_PARTITIONS_OFFSETS:
        'LIST_CONSUMER_GROUP_LATEST_TOPIC_PARTITIONS_OFFSETS',
    LIST_CONSUMER_GROUP_LATEST_TOPIC_PARTITIONS_OFFSETS_PENDING:
        'LIST_CONSUMER_GROUP_LATEST_TOPIC_PARTITIONS_OFFSETS_PENDING',
    LIST_CONSUMER_GROUP_LATEST_TOPIC_PARTITIONS_OFFSETS_FULFILLED:
        'LIST_CONSUMER_GROUP_LATEST_TOPIC_PARTITIONS_OFFSETS_FULFILLED',
    LIST_CONSUMER_GROUP_LATEST_TOPIC_PARTITIONS_OFFSETS_REJECTED:
        'LIST_CONSUMER_GROUP_LATEST_TOPIC_PARTITIONS_OFFSETS_REJECTED',
};

export default offsetTypes;
