const producerTypes = {
    PRODUCE_BLAZING_RECORD: 'PRODUCE_BLAZING_RECORD',
    PRODUCE_BLAZING_RECORD_PENDING: 'PRODUCE_BLAZING_RECORD_PENDING',
    PRODUCE_BLAZING_RECORD_FULFILLED: 'PRODUCE_BLAZING_RECORD_FULFILLED',
    PRODUCE_BLAZING_RECORD_REJECTED: 'PRODUCE_BLAZING_RECORD_REJECTED',

    GET_PRODUCER_CONFIGURATION: 'GET_PRODUCER_CONFIGURATION',
    GET_PRODUCER_CONFIGURATION_PENDING: 'GET_PRODUCER_CONFIGURATION_PENDING',
    GET_PRODUCER_CONFIGURATION_FULFILLED:
        'GET_PRODUCER_CONFIGURATION_FULFILLED',
    GET_PRODUCER_CONFIGURATION_REJECTED: 'GET_PRODUCER_CONFIGURATION_REJECTED',

    GET_PRODUCER_COMPLETE_CONFIGURATION: 'GET_PRODUCER_COMPLETE_CONFIGURATION',
    GET_PRODUCER_COMPLETE_CONFIGURATION_PENDING:
        'GET_PRODUCER_COMPLETE_CONFIGURATION_PENDING',
    GET_PRODUCER_COMPLETE_CONFIGURATION_FULFILLED:
        'GET_PRODUCER_COMPLETE_CONFIGURATION_FULFILLED',
    GET_PRODUCER_COMPLETE_CONFIGURATION_REJECTED:
        'GET_PRODUCER_COMPLETE_CONFIGURATION_REJECTED',

    EDIT_PRODUCER_CONFIGURATION: 'EDIT_PRODUCER_CONFIGURATION',
    EDIT_PRODUCER_CONFIGURATION_PENDING: 'EDIT_PRODUCER_CONFIGURATION_PENDING',
    EDIT_PRODUCER_CONFIGURATION_FULFILLED:
        'EDIT_PRODUCER_CONFIGURATION_FULFILLED',
    EDIT_PRODUCER_CONFIGURATION_REJECTED:
        'EDIT_PRODUCER_CONFIGURATION_REJECTED',

    IMPORT_BLAZING_RECORDS: 'IMPORT_BLAZING_RECORDS',
    IMPORT_BLAZING_RECORDS_PENDING: 'IMPORT_BLAZING_RECORDS_PENDING',
    IMPORT_BLAZING_RECORDS_FULFILLED: 'IMPORT_BLAZING_RECORDS_FULFILLED',
    IMPORT_BLAZING_RECORDS_REJECTED: 'IMPORT_BLAZING_RECORDS_REJECTED',
};

export default producerTypes;
