const quotaTypes = {
    DESCRIBE_QUOTAS: 'DESCRIBE_QUOTAS',
    DESCRIBE_QUOTAS_PENDING: 'DESCRIBE_QUOTAS_PENDING',
    DESCRIBE_QUOTAS_FULFILLED: 'DESCRIBE_QUOTAS_FULFILLED',
    DESCRIBE_QUOTAS_REJECTED: 'DESCRIBE_QUOTAS_REJECTED',

    ALTER_QUOTA: 'ALTER_QUOTA',
    ALTER_QUOTA_PENDING: 'ALTER_QUOTA_PENDING',
    ALTER_QUOTA_FULFILLED: 'ALTER_QUOTA_FULFILLED',
    ALTER_QUOTA_REJECTED: 'ALTER_QUOTA_REJECTED',
};

export default quotaTypes;
