const consumerTypes = {
    GET_CONSUMER_CONFIGURATION: 'GET_CONSUMER_CONFIGURATION',
    GET_CONSUMER_CONFIGURATION_PENDING: 'GET_CONSUMER_CONFIGURATION_PENDING',
    GET_CONSUMER_CONFIGURATION_FULFILLED:
        'GET_CONSUMER_CONFIGURATION_FULFILLED',
    GET_CONSUMER_CONFIGURATION_REJECTED: 'GET_CONSUMER_CONFIGURATION_REJECTED',

    GET_CONSUMER_COMPLETE_CONFIGURATION: 'GET_CONSUMER_COMPLETE_CONFIGURATION',
    GET_CONSUMER_COMPLETE_CONFIGURATION_PENDING:
        'GET_CONSUMER_COMPLETE_CONFIGURATION_PENDING',
    GET_CONSUMER_COMPLETE_CONFIGURATION_FULFILLED:
        'GET_CONSUMER_COMPLETE_CONFIGURATION_FULFILLED',
    GET_CONSUMER_COMPLETE_CONFIGURATION_REJECTED:
        'GET_CONSUMER_COMPLETE_CONFIGURATION_REJECTED',

    EDIT_CONSUMER_CONFIGURATION: 'EDIT_CONSUMER_CONFIGURATION',
    EDIT_CONSUMER_CONFIGURATION_PENDING: 'EDIT_CONSUMER_CONFIGURATION_PENDING',
    EDIT_CONSUMER_CONFIGURATION_FULFILLED:
        'EDIT_CONSUMER_CONFIGURATION_FULFILLED',
    EDIT_CONSUMER_CONFIGURATION_REJECTED:
        'EDIT_CONSUMER_CONFIGURATION_REJECTED',

    EXPORT_CONSUMER_RECORDS: 'EXPORT_CONSUMER_RECORDS',
    EXPORT_CONSUMER_RECORDS_PENDING: 'EXPORT_CONSUMER_RECORDS_PENDING',
    EXPORT_CONSUMER_RECORDS_FULFILLED: 'EXPORT_CONSUMER_RECORDS_FULFILLED',
    EXPORT_CONSUMER_RECORDS_REJECTED: 'EXPORT_CONSUMER_RECORDS_REJECTED',
};

export default consumerTypes;
