package com.redadani1997.blazingkraft.common.actions.management;

public class ManagementKafkaConnectActions {
    public static final String MANAGEMENT_KAFKA_CONNECT_FEATURE_ENABLED =
            "MANAGEMENT_KAFKA_CONNECT_FEATURE_ENABLED";
    public static final String MANAGEMENT_DESCRIBE_KAFKA_CONNECTS =
            "MANAGEMENT_DESCRIBE_KAFKA_CONNECTS";
    public static final String MANAGEMENT_CREATE_KAFKA_CONNECT = "MANAGEMENT_CREATE_KAFKA_CONNECT";
    public static final String MANAGEMENT_TEST_KAFKA_CONNECT_CONNECTIVITY =
            "MANAGEMENT_TEST_KAFKA_CONNECT_CONNECTIVITY";
    public static final String MANAGEMENT_EDIT_KAFKA_CONNECT = "MANAGEMENT_EDIT_KAFKA_CONNECT";
    public static final String MANAGEMENT_DELETE_KAFKA_CONNECT = "MANAGEMENT_DELETE_KAFKA_CONNECT";
    public static final String MANAGEMENT_EXPORT_KAFKA_CONNECT = "MANAGEMENT_EXPORT_KAFKA_CONNECT";
    public static final String MANAGEMENT_IMPORT_KAFKA_CONNECT = "MANAGEMENT_IMPORT_KAFKA_CONNECT";
}
