const schemaRegistryTypes = {
    GET_SUBJECTS_META: 'GET_SUBJECTS_META',
    GET_SUBJECTS_META_PENDING: 'GET_SUBJECTS_META_PENDING',
    GET_SUBJECTS_META_FULFILLED: 'GET_SUBJECTS_META_FULFILLED',
    GET_SUBJECTS_META_REJECTED: 'GET_SUBJECTS_META_REJECTED',

    GET_SCHEMA_REGISTRY_CONFIG: 'GET_SCHEMA_REGISTRY_CONFIG',
    GET_SCHEMA_REGISTRY_CONFIG_PENDING: 'GET_SCHEMA_REGISTRY_CONFIG_PENDING',
    GET_SCHEMA_REGISTRY_CONFIG_FULFILLED:
        'GET_SCHEMA_REGISTRY_CONFIG_FULFILLED',
    GET_SCHEMA_REGISTRY_CONFIG_REJECTED: 'GET_SCHEMA_REGISTRY_CONFIG_REJECTED',

    GET_SUBJECTS_DESCRIPTION: 'GET_SUBJECTS_DESCRIPTION',
    GET_SUBJECTS_DESCRIPTION_PENDING: 'GET_SUBJECTS_DESCRIPTION_PENDING',
    GET_SUBJECTS_DESCRIPTION_FULFILLED: 'GET_SUBJECTS_DESCRIPTION_FULFILLED',
    GET_SUBJECTS_DESCRIPTION_REJECTED: 'GET_SUBJECTS_DESCRIPTION_REJECTED',

    CREATE_SCHEMA_REGISTRY: 'CREATE_SCHEMA_REGISTRY',
    CREATE_SCHEMA_REGISTRY_PENDING: 'CREATE_SCHEMA_REGISTRY_PENDING',
    CREATE_SCHEMA_REGISTRY_FULFILLED: 'CREATE_SCHEMA_REGISTRY_FULFILLED',
    CREATE_SCHEMA_REGISTRY_REJECTED: 'CREATE_SCHEMA_REGISTRY_REJECTED',

    EDIT_SCHEMA_REGISTRY: 'EDIT_SCHEMA_REGISTRY',
    EDIT_SCHEMA_REGISTRY_PENDING: 'EDIT_SCHEMA_REGISTRY_PENDING',
    EDIT_SCHEMA_REGISTRY_FULFILLED: 'EDIT_SCHEMA_REGISTRY_FULFILLED',
    EDIT_SCHEMA_REGISTRY_REJECTED: 'EDIT_SCHEMA_REGISTRY_REJECTED',

    DELETE_SCHEMA_REGISTRY: 'DELETE_SCHEMA_REGISTRY',
    DELETE_SCHEMA_REGISTRY_PENDING: 'DELETE_SCHEMA_REGISTRY_PENDING',
    DELETE_SCHEMA_REGISTRY_FULFILLED: 'DELETE_SCHEMA_REGISTRY_FULFILLED',
    DELETE_SCHEMA_REGISTRY_REJECTED: 'DELETE_SCHEMA_REGISTRY_REJECTED',

    GET_SCHEMA_REGISTRY_DETAILS: 'GET_SCHEMA_REGISTRY_DETAILS',
    GET_SCHEMA_REGISTRY_DETAILS_PENDING: 'GET_SCHEMA_REGISTRY_DETAILS_PENDING',
    GET_SCHEMA_REGISTRY_DETAILS_FULFILLED:
        'GET_SCHEMA_REGISTRY_DETAILS_FULFILLED',
    GET_SCHEMA_REGISTRY_DETAILS_REJECTED:
        'GET_SCHEMA_REGISTRY_DETAILS_REJECTED',

    TEST_SCHEMA_REGISTRY_CLIENT_CONNECTIVITY:
        'TEST_SCHEMA_REGISTRY_CLIENT_CONNECTIVITY',
    TEST_SCHEMA_REGISTRY_CLIENT_CONNECTIVITY_PENDING:
        'TEST_SCHEMA_REGISTRY_CLIENT_CONNECTIVITY_PENDING',
    TEST_SCHEMA_REGISTRY_CLIENT_CONNECTIVITY_FULFILLED:
        'TEST_SCHEMA_REGISTRY_CLIENT_CONNECTIVITY_FULFILLED',
    TEST_SCHEMA_REGISTRY_CLIENT_CONNECTIVITY_REJECTED:
        'TEST_SCHEMA_REGISTRY_CLIENT_CONNECTIVITY_REJECTED',

    TEST_SCHEMA_REGISTRY_JMX_CONNECTIVITY:
        'TEST_SCHEMA_REGISTRY_JMX_CONNECTIVITY',
    TEST_SCHEMA_REGISTRY_JMX_CONNECTIVITY_PENDING:
        'TEST_SCHEMA_REGISTRY_JMX_CONNECTIVITY_PENDING',
    TEST_SCHEMA_REGISTRY_JMX_CONNECTIVITY_FULFILLED:
        'TEST_SCHEMA_REGISTRY_JMX_CONNECTIVITY_FULFILLED',
    TEST_SCHEMA_REGISTRY_JMX_CONNECTIVITY_REJECTED:
        'TEST_SCHEMA_REGISTRY_JMX_CONNECTIVITY_REJECTED',

    GET_SCHEMA_REGISTRY_META: 'GET_SCHEMA_REGISTRY_META',
    GET_SCHEMA_REGISTRY_META_PENDING: 'GET_SCHEMA_REGISTRY_META_PENDING',
    GET_SCHEMA_REGISTRY_META_FULFILLED: 'GET_SCHEMA_REGISTRY_META_FULFILLED',
    GET_SCHEMA_REGISTRY_META_REJECTED: 'GET_SCHEMA_REGISTRY_META_REJECTED',

    CREATE_SUBJECT: 'CREATE_SUBJECT',
    CREATE_SUBJECT_PENDING: 'CREATE_SUBJECT_PENDING',
    CREATE_SUBJECT_FULFILLED: 'CREATE_SUBJECT_FULFILLED',
    CREATE_SUBJECT_REJECTED: 'CREATE_SUBJECT_REJECTED',

    CREATE_SUBJECT_VERSION: 'CREATE_SUBJECT_VERSION',
    CREATE_SUBJECT_VERSION_PENDING: 'CREATE_SUBJECT_VERSION_PENDING',
    CREATE_SUBJECT_VERSION_FULFILLED: 'CREATE_SUBJECT_VERSION_FULFILLED',
    CREATE_SUBJECT_VERSION_REJECTED: 'CREATE_SUBJECT_VERSION_REJECTED',

    GET_SUBJECTS_VERSIONS: 'GET_SUBJECTS_VERSIONS',
    GET_SUBJECTS_VERSIONS_PENDING: 'GET_SUBJECTS_VERSIONS_PENDING',
    GET_SUBJECTS_VERSIONS_FULFILLED: 'GET_SUBJECTS_VERSIONS_FULFILLED',
    GET_SUBJECTS_VERSIONS_REJECTED: 'GET_SUBJECTS_VERSIONS_REJECTED',

    GET_SUBJECT_DETAILS: 'GET_SUBJECT_DETAILS',
    GET_SUBJECT_DETAILS_PENDING: 'GET_SUBJECT_DETAILS_PENDING',
    GET_SUBJECT_DETAILS_FULFILLED: 'GET_SUBJECT_DETAILS_FULFILLED',
    GET_SUBJECT_DETAILS_REJECTED: 'GET_SUBJECT_DETAILS_REJECTED',

    GET_TOPIC_SUBJECT_DETAILS: 'GET_TOPIC_SUBJECT_DETAILS',
    GET_TOPIC_SUBJECT_DETAILS_PENDING: 'GET_TOPIC_SUBJECT_DETAILS_PENDING',
    GET_TOPIC_SUBJECT_DETAILS_FULFILLED: 'GET_TOPIC_SUBJECT_DETAILS_FULFILLED',
    GET_TOPIC_SUBJECT_DETAILS_REJECTED: 'GET_TOPIC_SUBJECT_DETAILS_REJECTED',

    DELETE_SUBJECT: 'DELETE_SUBJECT',
    DELETE_SUBJECT_PENDING: 'DELETE_SUBJECT_PENDING',
    DELETE_SUBJECT_FULFILLED: 'DELETE_SUBJECT_FULFILLED',
    DELETE_SUBJECT_REJECTED: 'DELETE_SUBJECT_REJECTED',

    DELETE_SCHEMA_VERSION: 'DELETE_SCHEMA_VERSION',
    DELETE_SCHEMA_VERSION_PENDING: 'DELETE_SCHEMA_VERSION_PENDING',
    DELETE_SCHEMA_VERSION_FULFILLED: 'DELETE_SCHEMA_VERSION_FULFILLED',
    DELETE_SCHEMA_VERSION_REJECTED: 'DELETE_SCHEMA_VERSION_REJECTED',

    DESCRIBE_SCHEMA_REGISTRY: 'DESCRIBE_SCHEMA_REGISTRY',
    DESCRIBE_SCHEMA_REGISTRY_PENDING: 'DESCRIBE_SCHEMA_REGISTRY_PENDING',
    DESCRIBE_SCHEMA_REGISTRY_FULFILLED: 'DESCRIBE_SCHEMA_REGISTRY_FULFILLED',
    DESCRIBE_SCHEMA_REGISTRY_REJECTED: 'DESCRIBE_SCHEMA_REGISTRY_REJECTED',

    GET_SCHEMA_REGISTRIES: 'GET_SCHEMA_REGISTRIES',
    GET_SCHEMA_REGISTRIES_PENDING: 'GET_SCHEMA_REGISTRIES_PENDING',
    GET_SCHEMA_REGISTRIES_FULFILLED: 'GET_SCHEMA_REGISTRIES_FULFILLED',
    GET_SCHEMA_REGISTRIES_REJECTED: 'GET_SCHEMA_REGISTRIES_REJECTED',

    UPDATE_SUBJECT_COMPATIBILITY: 'UPDATE_SUBJECT_COMPATIBILITY',
    UPDATE_SUBJECT_COMPATIBILITY_PENDING:
        'UPDATE_SUBJECT_COMPATIBILITY_PENDING',
    UPDATE_SUBJECT_COMPATIBILITY_FULFILLED:
        'UPDATE_SUBJECT_COMPATIBILITY_FULFILLED',
    UPDATE_SUBJECT_COMPATIBILITY_REJECTED:
        'UPDATE_SUBJECT_COMPATIBILITY_REJECTED',

    UPDATE_SUBJECT_MODE: 'UPDATE_SUBJECT_MODE',
    UPDATE_SUBJECT_MODE_PENDING: 'UPDATE_SUBJECT_MODE_PENDING',
    UPDATE_SUBJECT_MODE_FULFILLED: 'UPDATE_SUBJECT_MODE_FULFILLED',
    UPDATE_SUBJECT_MODE_REJECTED: 'UPDATE_SUBJECT_MODE_REJECTED',

    UPDATE_SCHEMA_REGISTRY_MODE: 'UPDATE_SCHEMA_REGISTRY_MODE',
    UPDATE_SCHEMA_REGISTRY_MODE_PENDING: 'UPDATE_SCHEMA_REGISTRY_MODE_PENDING',
    UPDATE_SCHEMA_REGISTRY_MODE_FULFILLED:
        'UPDATE_SCHEMA_REGISTRY_MODE_FULFILLED',
    UPDATE_SCHEMA_REGISTRY_MODE_REJECTED:
        'UPDATE_SCHEMA_REGISTRY_MODE_REJECTED',

    UPDATE_SCHEMA_REGISTRY_COMPATIBILITY:
        'UPDATE_SCHEMA_REGISTRY_COMPATIBILITY',
    UPDATE_SCHEMA_REGISTRY_COMPATIBILITY_PENDING:
        'UPDATE_SCHEMA_REGISTRY_COMPATIBILITY_PENDING',
    UPDATE_SCHEMA_REGISTRY_COMPATIBILITY_FULFILLED:
        'UPDATE_SCHEMA_REGISTRY_COMPATIBILITY_FULFILLED',
    UPDATE_SCHEMA_REGISTRY_COMPATIBILITY_REJECTED:
        'UPDATE_SCHEMA_REGISTRY_COMPATIBILITY_REJECTED',
};

export default schemaRegistryTypes;
