const githubTypes = {
    GET_LATEST_RELEASE: 'GET_LATEST_RELEASE',
    GET_LATEST_RELEASE_PENDING: 'GET_LATEST_RELEASE_PENDING',
    GET_LATEST_RELEASE_FULFILLED: 'GET_LATEST_RELEASE_FULFILLED',
    GET_LATEST_RELEASE_REJECTED: 'GET_LATEST_RELEASE_REJECTED',
};

export default githubTypes;
