const connectPluginTypes = {
    LIST_ALL_CONNECT_PLUGINS: 'LIST_ALL_CONNECT_PLUGINS',
    LIST_ALL_CONNECT_PLUGINS_PENDING: 'LIST_ALL_CONNECT_PLUGINS_PENDING',
    LIST_ALL_CONNECT_PLUGINS_FULFILLED: 'LIST_ALL_CONNECT_PLUGINS_FULFILLED',
    LIST_ALL_CONNECT_PLUGINS_REJECTED: 'LIST_ALL_CONNECT_PLUGINS_REJECTED',

    LIST_CONNECTOR_CONNECT_PLUGINS: 'LIST_CONNECTOR_CONNECT_PLUGINS',
    LIST_CONNECTOR_CONNECT_PLUGINS_PENDING:
        'LIST_CONNECTOR_CONNECT_PLUGINS_PENDING',
    LIST_CONNECTOR_CONNECT_PLUGINS_FULFILLED:
        'LIST_CONNECTOR_CONNECT_PLUGINS_FULFILLED',
    LIST_CONNECTOR_CONNECT_PLUGINS_REJECTED:
        'LIST_CONNECTOR_CONNECT_PLUGINS_REJECTED',

    GET_CONNECT_PLUGIN_CONFIG_KEYS: 'GET_CONNECT_PLUGIN_CONFIG_KEYS',
    GET_CONNECT_PLUGIN_CONFIG_KEYS_PENDING:
        'GET_CONNECT_PLUGIN_CONFIG_KEYS_PENDING',
    GET_CONNECT_PLUGIN_CONFIG_KEYS_FULFILLED:
        'GET_CONNECT_PLUGIN_CONFIG_KEYS_FULFILLED',
    GET_CONNECT_PLUGIN_CONFIG_KEYS_REJECTED:
        'GET_CONNECT_PLUGIN_CONFIG_KEYS_REJECTED',

    CLEAR_CONNECT_PLUGIN_CONFIG_KEYS: 'CLEAR_CONNECT_PLUGIN_CONFIG_KEYS',

    VALIDATE_CONFIGURATIONS: 'VALIDATE_CONFIGURATIONS',
    VALIDATE_CONFIGURATIONS_PENDING: 'VALIDATE_CONFIGURATIONS_PENDING',
    VALIDATE_CONFIGURATIONS_FULFILLED: 'VALIDATE_CONFIGURATIONS_FULFILLED',
    VALIDATE_CONFIGURATIONS_REJECTED: 'VALIDATE_CONFIGURATIONS_REJECTED',
};

export default connectPluginTypes;
