import BlazingConsumerDeserializerComponent from './BlazingConsumerDeserializerComponent';

const BlazingConsumerDeserializer = BlazingConsumerDeserializerComponent;

export default BlazingConsumerDeserializer;
