const kafkaConnectTypes = {
    GET_ALL_KAFKA_CONNECTS: 'GET_ALL_KAFKA_CONNECTS',
    GET_ALL_KAFKA_CONNECTS_PENDING: 'GET_ALL_KAFKA_CONNECTS_PENDING',
    GET_ALL_KAFKA_CONNECTS_FULFILLED: 'GET_ALL_KAFKA_CONNECTS_FULFILLED',
    GET_ALL_KAFKA_CONNECTS_REJECTED: 'GET_ALL_KAFKA_CONNECTS_REJECTED',

    CREATE_KAFKA_CONNECT: 'CREATE_KAFKA_CONNECT',
    CREATE_KAFKA_CONNECT_PENDING: 'CREATE_KAFKA_CONNECT_PENDING',
    CREATE_KAFKA_CONNECT_FULFILLED: 'CREATE_KAFKA_CONNECT_FULFILLED',
    CREATE_KAFKA_CONNECT_REJECTED: 'CREATE_KAFKA_CONNECT_REJECTED',

    TEST_KAFKA_CONNECT_CLIENT_CONNECTIVITY:
        'TEST_KAFKA_CONNECT_CLIENT_CONNECTIVITY',
    TEST_KAFKA_CONNECT_CLIENT_CONNECTIVITY_PENDING:
        'TEST_KAFKA_CONNECT_CLIENT_CONNECTIVITY_PENDING',
    TEST_KAFKA_CONNECT_CLIENT_CONNECTIVITY_FULFILLED:
        'TEST_KAFKA_CONNECT_CLIENT_CONNECTIVITY_FULFILLED',
    TEST_KAFKA_CONNECT_CLIENT_CONNECTIVITY_REJECTED:
        'TEST_KAFKA_CONNECT_CLIENT_CONNECTIVITY_REJECTED',

    TEST_KAFKA_CONNECT_JMX_CONNECTIVITY: 'TEST_KAFKA_CONNECT_JMX_CONNECTIVITY',
    TEST_KAFKA_CONNECT_JMX_CONNECTIVITY_PENDING:
        'TEST_KAFKA_CONNECT_JMX_CONNECTIVITY_PENDING',
    TEST_KAFKA_CONNECT_JMX_CONNECTIVITY_FULFILLED:
        'TEST_KAFKA_CONNECT_JMX_CONNECTIVITY_FULFILLED',
    TEST_KAFKA_CONNECT_JMX_CONNECTIVITY_REJECTED:
        'TEST_KAFKA_CONNECT_JMX_CONNECTIVITY_REJECTED',

    GET_KAFKA_CONNECT_META: 'GET_KAFKA_CONNECT_META',
    GET_KAFKA_CONNECT_META_PENDING: 'GET_KAFKA_CONNECT_META_PENDING',
    GET_KAFKA_CONNECT_META_FULFILLED: 'GET_KAFKA_CONNECT_META_FULFILLED',
    GET_KAFKA_CONNECT_META_REJECTED: 'GET_KAFKA_CONNECT_META_REJECTED',

    GET_KAFKA_CONNECT_DETAILS: 'GET_KAFKA_CONNECT_DETAILS',
    GET_KAFKA_CONNECT_DETAILS_PENDING: 'GET_KAFKA_CONNECT_DETAILS_PENDING',
    GET_KAFKA_CONNECT_DETAILS_FULFILLED: 'GET_KAFKA_CONNECT_DETAILS_FULFILLED',
    GET_KAFKA_CONNECT_DETAILS_REJECTED: 'GET_KAFKA_CONNECT_DETAILS_REJECTED',

    DELETE_KAFKA_CONNECT: 'DELETE_KAFKA_CONNECT',
    DELETE_KAFKA_CONNECT_PENDING: 'DELETE_KAFKA_CONNECT_PENDING',
    DELETE_KAFKA_CONNECT_FULFILLED: 'DELETE_KAFKA_CONNECT_FULFILLED',
    DELETE_KAFKA_CONNECT_REJECTED: 'DELETE_KAFKA_CONNECT_REJECTED',

    EDIT_KAFKA_CONNECT: 'EDIT_KAFKA_CONNECT',
    EDIT_KAFKA_CONNECT_PENDING: 'EDIT_KAFKA_CONNECT_PENDING',
    EDIT_KAFKA_CONNECT_FULFILLED: 'EDIT_KAFKA_CONNECT_FULFILLED',
    EDIT_KAFKA_CONNECT_REJECTED: 'EDIT_KAFKA_CONNECT_REJECTED',

    DESCRIBE_KAFKA_CONNECT: 'DESCRIBE_KAFKA_CONNECT',
    DESCRIBE_KAFKA_CONNECT_PENDING: 'DESCRIBE_KAFKA_CONNECT_PENDING',
    DESCRIBE_KAFKA_CONNECT_FULFILLED: 'DESCRIBE_KAFKA_CONNECT_FULFILLED',
    DESCRIBE_KAFKA_CONNECT_REJECTED: 'DESCRIBE_KAFKA_CONNECT_REJECTED',

    MONITOR_KAFKA_CONNECT: 'MONITOR_KAFKA_CONNECT',
    MONITOR_KAFKA_CONNECT_PENDING: 'MONITOR_KAFKA_CONNECT_PENDING',
    MONITOR_KAFKA_CONNECT_FULFILLED: 'MONITOR_KAFKA_CONNECT_FULFILLED',
    MONITOR_KAFKA_CONNECT_REJECTED: 'MONITOR_KAFKA_CONNECT_REJECTED',
};

export default kafkaConnectTypes;
