const ksqlDbEcosystemTypes = {
    GET_ALL_KSQLDB_CONNECTORS: 'GET_ALL_KSQLDB_CONNECTORS',
    GET_ALL_KSQLDB_CONNECTORS_PENDING: 'GET_ALL_KSQLDB_CONNECTORS_PENDING',
    GET_ALL_KSQLDB_CONNECTORS_FULFILLED: 'GET_ALL_KSQLDB_CONNECTORS_FULFILLED',
    GET_ALL_KSQLDB_CONNECTORS_REJECTED: 'GET_ALL_KSQLDB_CONNECTORS_REJECTED',

    CREATE_KSQLDB_CONNECTOR: 'CREATE_KSQLDB_CONNECTOR',
    CREATE_KSQLDB_CONNECTOR_PENDING: 'CREATE_KSQLDB_CONNECTOR_PENDING',
    CREATE_KSQLDB_CONNECTOR_FULFILLED: 'CREATE_KSQLDB_CONNECTOR_FULFILLED',
    CREATE_KSQLDB_CONNECTOR_REJECTED: 'CREATE_KSQLDB_CONNECTOR_REJECTED',

    DELETE_KSQLDB_CONNECTOR: 'DELETE_KSQLDB_CONNECTOR',
    DELETE_KSQLDB_CONNECTOR_PENDING: 'DELETE_KSQLDB_CONNECTOR_PENDING',
    DELETE_KSQLDB_CONNECTOR_FULFILLED: 'DELETE_KSQLDB_CONNECTOR_FULFILLED',
    DELETE_KSQLDB_CONNECTOR_REJECTED: 'DELETE_KSQLDB_CONNECTOR_REJECTED',

    GET_ALL_KSQLDB_TOPICS: 'GET_ALL_KSQLDB_TOPICS',
    GET_ALL_KSQLDB_TOPICS_PENDING: 'GET_ALL_KSQLDB_TOPICS_PENDING',
    GET_ALL_KSQLDB_TOPICS_FULFILLED: 'GET_ALL_KSQLDB_TOPICS_FULFILLED',
    GET_ALL_KSQLDB_TOPICS_REJECTED: 'GET_ALL_KSQLDB_TOPICS_REJECTED',

    GET_ALL_KSQLDB_TABLES: 'GET_ALL_KSQLDB_TABLES',
    GET_ALL_KSQLDB_TABLES_PENDING: 'GET_ALL_KSQLDB_TABLES_PENDING',
    GET_ALL_KSQLDB_TABLES_FULFILLED: 'GET_ALL_KSQLDB_TABLES_FULFILLED',
    GET_ALL_KSQLDB_TABLES_REJECTED: 'GET_ALL_KSQLDB_TABLES_REJECTED',

    GET_ALL_KSQLDB_STREAMS: 'GET_ALL_KSQLDB_STREAMS',
    GET_ALL_KSQLDB_STREAMS_PENDING: 'GET_ALL_KSQLDB_STREAMS_PENDING',
    GET_ALL_KSQLDB_STREAMS_FULFILLED: 'GET_ALL_KSQLDB_STREAMS_FULFILLED',
    GET_ALL_KSQLDB_STREAMS_REJECTED: 'GET_ALL_KSQLDB_STREAMS_REJECTED',

    GET_ALL_KSQLDB_QUERIES: 'GET_ALL_KSQLDB_QUERIES',
    GET_ALL_KSQLDB_QUERIES_PENDING: 'GET_ALL_KSQLDB_QUERIES_PENDING',
    GET_ALL_KSQLDB_QUERIES_FULFILLED: 'GET_ALL_KSQLDB_QUERIES_FULFILLED',
    GET_ALL_KSQLDB_QUERIES_REJECTED: 'GET_ALL_KSQLDB_QUERIES_REJECTED',

    KSQLDB_EDITOR_EXECUTE_QUERY: 'KSQLDB_EDITOR_EXECUTE_QUERY',
    KSQLDB_EDITOR_EXECUTE_QUERY_PENDING: 'KSQLDB_EDITOR_EXECUTE_QUERY_PENDING',
    KSQLDB_EDITOR_EXECUTE_QUERY_FULFILLED:
        'KSQLDB_EDITOR_EXECUTE_QUERY_FULFILLED',
    KSQLDB_EDITOR_EXECUTE_QUERY_REJECTED:
        'KSQLDB_EDITOR_EXECUTE_QUERY_REJECTED',

    KSQLDB_EDITOR_EXECUTE_STATEMENT: 'KSQLDB_EDITOR_EXECUTE_STATEMENT',
    KSQLDB_EDITOR_EXECUTE_STATEMENT_PENDING:
        'KSQLDB_EDITOR_EXECUTE_STATEMENT_PENDING',
    KSQLDB_EDITOR_EXECUTE_STATEMENT_FULFILLED:
        'KSQLDB_EDITOR_EXECUTE_STATEMENT_FULFILLED',
    KSQLDB_EDITOR_EXECUTE_STATEMENT_REJECTED:
        'KSQLDB_EDITOR_EXECUTE_STATEMENT_REJECTED',

    KSQLDB_EDITOR_CLEAR_ROWS: 'KSQLDB_EDITOR_CLEAR_ROWS',
};

export default ksqlDbEcosystemTypes;
