const clusterTypes = {
    GET_ALL_CLUSTERS: 'GET_ALL_CLUSTERS',
    GET_ALL_CLUSTERS_PENDING: 'GET_ALL_CLUSTERS_PENDING',
    GET_ALL_CLUSTERS_FULFILLED: 'GET_ALL_CLUSTERS_FULFILLED',
    GET_ALL_CLUSTERS_REJECTED: 'GET_ALL_CLUSTERS_REJECTED',

    GET_CLUSTER_BROKERS_DETAILS: 'GET_CLUSTER_BROKERS_DETAILS',
    GET_CLUSTER_BROKERS_DETAILS_PENDING: 'GET_CLUSTER_BROKERS_DETAILS_PENDING',
    GET_CLUSTER_BROKERS_DETAILS_FULFILLED:
        'GET_CLUSTER_BROKERS_DETAILS_FULFILLED',
    GET_CLUSTER_BROKERS_DETAILS_REJECTED:
        'GET_CLUSTER_BROKERS_DETAILS_REJECTED',

    GET_CLUSTER_BROKER_CONFIGURATION: 'GET_CLUSTER_BROKER_CONFIGURATION',
    GET_CLUSTER_BROKER_CONFIGURATION_PENDING:
        'GET_CLUSTER_BROKER_CONFIGURATION_PENDING',
    GET_CLUSTER_BROKER_CONFIGURATION_FULFILLED:
        'GET_CLUSTER_BROKER_CONFIGURATION_FULFILLED',
    GET_CLUSTER_BROKER_CONFIGURATION_REJECTED:
        'GET_CLUSTER_BROKER_CONFIGURATION_REJECTED',

    MONITOR_CLUSTER: 'MONITOR_CLUSTER',
    MONITOR_CLUSTER_PENDING: 'MONITOR_CLUSTER_PENDING',
    MONITOR_CLUSTER_FULFILLED: 'MONITOR_CLUSTER_FULFILLED',
    MONITOR_CLUSTER_REJECTED: 'MONITOR_CLUSTER_REJECTED',

    CREATE_CLUSTER: 'CREATE_CLUSTER',
    CREATE_CLUSTER_PENDING: 'CREATE_CLUSTER_PENDING',
    CREATE_CLUSTER_FULFILLED: 'CREATE_CLUSTER_FULFILLED',
    CREATE_CLUSTER_REJECTED: 'CREATE_CLUSTER_REJECTED',

    DELETE_CLUSTER: 'DELETE_CLUSTER',
    DELETE_CLUSTER_PENDING: 'DELETE_CLUSTER_PENDING',
    DELETE_CLUSTER_FULFILLED: 'DELETE_CLUSTER_FULFILLED',
    DELETE_CLUSTER_REJECTED: 'DELETE_CLUSTER_REJECTED',

    EDIT_CLUSTER: 'EDIT_CLUSTER',
    EDIT_CLUSTER_PENDING: 'EDIT_CLUSTER_PENDING',
    EDIT_CLUSTER_FULFILLED: 'EDIT_CLUSTER_FULFILLED',
    EDIT_CLUSTER_REJECTED: 'EDIT_CLUSTER_REJECTED',

    TEST_CLUSTER_CLIENT_CONNECTIVITY: 'TEST_CLUSTER_CLIENT_CONNECTIVITY',
    TEST_CLUSTER_CLIENT_CONNECTIVITY_PENDING:
        'TEST_CLUSTER_CLIENT_CONNECTIVITY_PENDING',
    TEST_CLUSTER_CLIENT_CONNECTIVITY_FULFILLED:
        'TEST_CLUSTER_CLIENT_CONNECTIVITY_FULFILLED',
    TEST_CLUSTER_CLIENT_CONNECTIVITY_REJECTED:
        'TEST_CLUSTER_CLIENT_CONNECTIVITY_REJECTED',

    TEST_CLUSTER_JMX_CONNECTIVITY: 'TEST_CLUSTER_JMX_CONNECTIVITY',
    TEST_CLUSTER_JMX_CONNECTIVITY_PENDING:
        'TEST_CLUSTER_JMX_CONNECTIVITY_PENDING',
    TEST_CLUSTER_JMX_CONNECTIVITY_FULFILLED:
        'TEST_CLUSTER_JMX_CONNECTIVITY_FULFILLED',
    TEST_CLUSTER_JMX_CONNECTIVITY_REJECTED:
        'TEST_CLUSTER_JMX_CONNECTIVITY_REJECTED',

    GET_CLUSTER_META: 'GET_CLUSTER_META',
    GET_CLUSTER_META_PENDING: 'GET_CLUSTER_META_PENDING',
    GET_CLUSTER_META_FULFILLED: 'GET_CLUSTER_META_FULFILLED',
    GET_CLUSTER_META_REJECTED: 'GET_CLUSTER_META_REJECTED',

    GET_CLUSTER_DETAILS: 'GET_CLUSTER_DETAILS',
    GET_CLUSTER_DETAILS_PENDING: 'GET_CLUSTER_DETAILS_PENDING',
    GET_CLUSTER_DETAILS_FULFILLED: 'GET_CLUSTER_DETAILS_FULFILLED',
    GET_CLUSTER_DETAILS_REJECTED: 'GET_CLUSTER_DETAILS_REJECTED',

    DESCRIBE_CLUSTER: 'DESCRIBE_CLUSTER',
    DESCRIBE_CLUSTER_PENDING: 'DESCRIBE_CLUSTER_PENDING',
    DESCRIBE_CLUSTER_FULFILLED: 'DESCRIBE_CLUSTER_FULFILLED',
    DESCRIBE_CLUSTER_REJECTED: 'DESCRIBE_CLUSTER_REJECTED',

    EXPORT_CLUSTER: 'EXPORT_CLUSTER',
    EXPORT_CLUSTER_PENDING: 'EXPORT_CLUSTER_PENDING',
    EXPORT_CLUSTER_FULFILLED: 'EXPORT_CLUSTER_FULFILLED',
    EXPORT_CLUSTER_REJECTED: 'EXPORT_CLUSTER_REJECTED',

    IMPORT_CLUSTER: 'IMPORT_CLUSTER',
    IMPORT_CLUSTER_PENDING: 'IMPORT_CLUSTER_PENDING',
    IMPORT_CLUSTER_FULFILLED: 'IMPORT_CLUSTER_FULFILLED',
    IMPORT_CLUSTER_REJECTED: 'IMPORT_CLUSTER_REJECTED',
};

export default clusterTypes;
