const filesTypes = {
    GET_FILES: 'GET_FILES',
    GET_FILES_PENDING: 'GET_FILES_PENDING',
    GET_FILES_FULFILLED: 'GET_FILES_FULFILLED',
    GET_FILES_REJECTED: 'GET_FILES_REJECTED',

    DELETE_FILE: 'DELETE_FILE',
    DELETE_FILE_PENDING: 'DELETE_FILE_PENDING',
    DELETE_FILE_FULFILLED: 'DELETE_FILE_FULFILLED',
    DELETE_FILE_REJECTED: 'DELETE_FILE_REJECTED',

    CREATE_FILE: 'CREATE_FILE',
    CREATE_FILE_PENDING: 'CREATE_FILE_PENDING',
    CREATE_FILE_FULFILLED: 'CREATE_FILE_FULFILLED',
    CREATE_FILE_REJECTED: 'CREATE_FILE_REJECTED',
};

export default filesTypes;
