const connectorTypes = {
    LIST_CONNECTORS: 'LIST_CONNECTORS',
    LIST_CONNECTORS_PENDING: 'LIST_CONNECTORS_PENDING',
    LIST_CONNECTORS_FULFILLED: 'LIST_CONNECTORS_FULFILLED',
    LIST_CONNECTORS_REJECTED: 'LIST_CONNECTORS_REJECTED',

    MONITOR_CONNECTOR_TASKS: 'MONITOR_CONNECTOR_TASKS',
    MONITOR_CONNECTOR_TASKS_PENDING: 'MONITOR_CONNECTOR_TASKS_PENDING',
    MONITOR_CONNECTOR_TASKS_FULFILLED: 'MONITOR_CONNECTOR_TASKS_FULFILLED',
    MONITOR_CONNECTOR_TASKS_REJECTED: 'MONITOR_CONNECTOR_TASKS_REJECTED',

    LIST_CONNECTORS_WITH_EXPANDED_INFO: 'LIST_CONNECTORS_WITH_EXPANDED_INFO',
    LIST_CONNECTORS_WITH_EXPANDED_INFO_PENDING:
        'LIST_CONNECTORS_WITH_EXPANDED_INFO_PENDING',
    LIST_CONNECTORS_WITH_EXPANDED_INFO_FULFILLED:
        'LIST_CONNECTORS_WITH_EXPANDED_INFO_FULFILLED',
    LIST_CONNECTORS_WITH_EXPANDED_INFO_REJECTED:
        'LIST_CONNECTORS_WITH_EXPANDED_INFO_REJECTED',

    LIST_CONNECTORS_WITH_EXPANDED_STATUS:
        'LIST_CONNECTORS_WITH_EXPANDED_STATUS',
    LIST_CONNECTORS_WITH_EXPANDED_STATUS_PENDING:
        'LIST_CONNECTORS_WITH_EXPANDED_STATUS_PENDING',
    LIST_CONNECTORS_WITH_EXPANDED_STATUS_FULFILLED:
        'LIST_CONNECTORS_WITH_EXPANDED_STATUS_FULFILLED',
    LIST_CONNECTORS_WITH_EXPANDED_STATUS_REJECTED:
        'LIST_CONNECTORS_WITH_EXPANDED_STATUS_REJECTED',

    LIST_CONNECTORS_WITH_EXPANDED_INFO_AND_STATUS:
        'LIST_CONNECTORS_WITH_EXPANDED_INFO_AND_STATUS',
    LIST_CONNECTORS_WITH_EXPANDED_INFO_AND_STATUS_PENDING:
        'LIST_CONNECTORS_WITH_EXPANDED_INFO_AND_STATUS_PENDING',
    LIST_CONNECTORS_WITH_EXPANDED_INFO_AND_STATUS_FULFILLED:
        'LIST_CONNECTORS_WITH_EXPANDED_INFO_AND_STATUS_FULFILLED',
    LIST_CONNECTORS_WITH_EXPANDED_INFO_AND_STATUS_REJECTED:
        'LIST_CONNECTORS_WITH_EXPANDED_INFO_AND_STATUS_REJECTED',

    CREATE_CONNECTOR: 'CREATE_CONNECTOR',
    CREATE_CONNECTOR_PENDING: 'CREATE_CONNECTOR_PENDING',
    CREATE_CONNECTOR_FULFILLED: 'CREATE_CONNECTOR_FULFILLED',
    CREATE_CONNECTOR_REJECTED: 'CREATE_CONNECTOR_REJECTED',

    DESTROY_CONNECTOR: 'DESTROY_CONNECTOR',
    DESTROY_CONNECTOR_PENDING: 'DESTROY_CONNECTOR_PENDING',
    DESTROY_CONNECTOR_FULFILLED: 'DESTROY_CONNECTOR_FULFILLED',
    DESTROY_CONNECTOR_REJECTED: 'DESTROY_CONNECTOR_REJECTED',

    GET_CONNECTOR_INFO: 'GET_CONNECTOR_INFO',
    GET_CONNECTOR_INFO_PENDING: 'GET_CONNECTOR_INFO_PENDING',
    GET_CONNECTOR_INFO_FULFILLED: 'GET_CONNECTOR_INFO_FULFILLED',
    GET_CONNECTOR_INFO_REJECTED: 'GET_CONNECTOR_INFO_REJECTED',

    GET_CONNECTOR_ACTIVE_TOPICS: 'GET_CONNECTOR_ACTIVE_TOPICS',
    GET_CONNECTOR_ACTIVE_TOPICS_PENDING: 'GET_CONNECTOR_ACTIVE_TOPICS_PENDING',
    GET_CONNECTOR_ACTIVE_TOPICS_FULFILLED:
        'GET_CONNECTOR_ACTIVE_TOPICS_FULFILLED',
    GET_CONNECTOR_ACTIVE_TOPICS_REJECTED:
        'GET_CONNECTOR_ACTIVE_TOPICS_REJECTED',

    GET_CONNECTOR_CONFIG: 'GET_CONNECTOR_CONFIG',
    GET_CONNECTOR_CONFIG_PENDING: 'GET_CONNECTOR_CONFIG_PENDING',
    GET_CONNECTOR_CONFIG_FULFILLED: 'GET_CONNECTOR_CONFIG_FULFILLED',
    GET_CONNECTOR_CONFIG_REJECTED: 'GET_CONNECTOR_CONFIG_REJECTED',

    GET_CONNECTOR_STATE_INFO: 'GET_CONNECTOR_STATE_INFO',
    GET_CONNECTOR_STATE_INFO_PENDING: 'GET_CONNECTOR_STATE_INFO_PENDING',
    GET_CONNECTOR_STATE_INFO_FULFILLED: 'GET_CONNECTOR_STATE_INFO_FULFILLED',
    GET_CONNECTOR_STATE_INFO_REJECTED: 'GET_CONNECTOR_STATE_INFO_REJECTED',

    PAUSE_CONNECTOR: 'PAUSE_CONNECTOR',
    PAUSE_CONNECTOR_PENDING: 'PAUSE_CONNECTOR_PENDING',
    PAUSE_CONNECTOR_FULFILLED: 'PAUSE_CONNECTOR_FULFILLED',
    PAUSE_CONNECTOR_REJECTED: 'PAUSE_CONNECTOR_REJECTED',

    EDIT_CONNECTOR_CONFIG: 'EDIT_CONNECTOR_CONFIG',
    EDIT_CONNECTOR_CONFIG_PENDING: 'EDIT_CONNECTOR_CONFIG_PENDING',
    EDIT_CONNECTOR_CONFIG_FULFILLED: 'EDIT_CONNECTOR_CONFIG_FULFILLED',
    EDIT_CONNECTOR_CONFIG_REJECTED: 'EDIT_CONNECTOR_CONFIG_REJECTED',

    RESET_CONNECTOR_ACTIVE_TOPICS: 'RESET_CONNECTOR_ACTIVE_TOPICS',
    RESET_CONNECTOR_ACTIVE_TOPICS_PENDING:
        'RESET_CONNECTOR_ACTIVE_TOPICS_PENDING',
    RESET_CONNECTOR_ACTIVE_TOPICS_FULFILLED:
        'RESET_CONNECTOR_ACTIVE_TOPICS_FULFILLED',
    RESET_CONNECTOR_ACTIVE_TOPICS_REJECTED:
        'RESET_CONNECTOR_ACTIVE_TOPICS_REJECTED',

    RESTART_CONNECTOR: 'RESTART_CONNECTOR',
    RESTART_CONNECTOR_PENDING: 'RESTART_CONNECTOR_PENDING',
    RESTART_CONNECTOR_FULFILLED: 'RESTART_CONNECTOR_FULFILLED',
    RESTART_CONNECTOR_REJECTED: 'RESTART_CONNECTOR_REJECTED',

    RESUME_CONNECTOR: 'RESUME_CONNECTOR',
    RESUME_CONNECTOR_PENDING: 'RESUME_CONNECTOR_PENDING',
    RESUME_CONNECTOR_FULFILLED: 'RESUME_CONNECTOR_FULFILLED',
    RESUME_CONNECTOR_REJECTED: 'RESUME_CONNECTOR_REJECTED',

    RESTART_CONNECTOR_TASK: 'RESTART_CONNECTOR_TASK',
    RESTART_CONNECTOR_TASK_PENDING: 'RESTART_CONNECTOR_TASK_PENDING',
    RESTART_CONNECTOR_TASK_FULFILLED: 'RESTART_CONNECTOR_TASK_FULFILLED',
    RESTART_CONNECTOR_TASK_REJECTED: 'RESTART_CONNECTOR_TASK_REJECTED',
};

export default connectorTypes;
