import PlaygroundValidationPreviewComponent from './PlaygroundValidationPreviewComponent';

const PlaygroundValidationPreview = PlaygroundValidationPreviewComponent;

export default PlaygroundValidationPreview;
