import { PermissionLabel } from '..';

const CONTENT_VALIDATION_PERMISSIONS = {
    CONTENT_VALIDATION_FEATURE_ENABLED: 'CONTENT_VALIDATION_FEATURE_ENABLED',
    CONTENT_VALIDATION_VALIDATE_SCHEMA: 'CONTENT_VALIDATION_VALIDATE_SCHEMA',
} as const;

const CONTENT_VALIDATION_PERMISSIONS_LIST = [
    CONTENT_VALIDATION_PERMISSIONS.CONTENT_VALIDATION_FEATURE_ENABLED,
    CONTENT_VALIDATION_PERMISSIONS.CONTENT_VALIDATION_VALIDATE_SCHEMA,
] as const;

const CONTENT_VALIDATION_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable Content Validation Feature',
        permission:
            CONTENT_VALIDATION_PERMISSIONS.CONTENT_VALIDATION_FEATURE_ENABLED,
    },
    {
        label: 'Validate Content',
        permission:
            CONTENT_VALIDATION_PERMISSIONS.CONTENT_VALIDATION_VALIDATE_SCHEMA,
    },
];

const ContentValidationPermissions = {
    CONTENT_VALIDATION_PERMISSIONS,
    CONTENT_VALIDATION_PERMISSIONS_LIST,
    CONTENT_VALIDATION_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { ContentValidationPermissions };
