import { PermissionLabel } from '..';

const OPENAPI_CONTENT_PERMISSIONS = {
    OPENAPI_CONTENT_FEATURE_ENABLED: 'OPENAPI_CONTENT_FEATURE_ENABLED',
    OPENAPI_CONTENT_VALIDATE_SCHEMA: 'OPENAPI_CONTENT_VALIDATE_SCHEMA',
} as const;

const OPENAPI_CONTENT_PERMISSIONS_LIST = [
    OPENAPI_CONTENT_PERMISSIONS.OPENAPI_CONTENT_FEATURE_ENABLED,
    OPENAPI_CONTENT_PERMISSIONS.OPENAPI_CONTENT_VALIDATE_SCHEMA,
] as const;

const OPENAPI_CONTENT_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable OpenAPI Content Feature',
        permission: OPENAPI_CONTENT_PERMISSIONS.OPENAPI_CONTENT_FEATURE_ENABLED,
    },
    {
        label: 'Validate OpenAPI Content Schema',
        permission: OPENAPI_CONTENT_PERMISSIONS.OPENAPI_CONTENT_VALIDATE_SCHEMA,
    },
];

const OpenAPIContentPermissions = {
    OPENAPI_CONTENT_PERMISSIONS,
    OPENAPI_CONTENT_PERMISSIONS_LIST,
    OPENAPI_CONTENT_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { OpenAPIContentPermissions };
