import { PermissionLabel } from '..';

const OPENAPI_DEFINITION_PERMISSIONS = {
    OPENAPI_DEFINITION_FEATURE_ENABLED: 'OPENAPI_DEFINITION_FEATURE_ENABLED',
    OPENAPI_DEFINITION_VALIDATE_SCHEMA: 'OPENAPI_DEFINITION_VALIDATE_SCHEMA',
} as const;

const OPENAPI_DEFINITION_PERMISSIONS_LIST = [
    OPENAPI_DEFINITION_PERMISSIONS.OPENAPI_DEFINITION_FEATURE_ENABLED,
    OPENAPI_DEFINITION_PERMISSIONS.OPENAPI_DEFINITION_VALIDATE_SCHEMA,
] as const;

const OPENAPI_DEFINITION_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable OpenAPI Definition Feature',
        permission:
            OPENAPI_DEFINITION_PERMISSIONS.OPENAPI_DEFINITION_FEATURE_ENABLED,
    },
    {
        label: 'Validate OpenAPI Definition Schema',
        permission:
            OPENAPI_DEFINITION_PERMISSIONS.OPENAPI_DEFINITION_VALIDATE_SCHEMA,
    },
];

const OpenAPIDefinitionPermissions = {
    OPENAPI_DEFINITION_PERMISSIONS,
    OPENAPI_DEFINITION_PERMISSIONS_LIST,
    OPENAPI_DEFINITION_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { OpenAPIDefinitionPermissions };
