import { PermissionLabel } from '..';

const SCHEMAS_CONTENT_PERMISSIONS = {
    SCHEMAS_CONTENT_FEATURE_ENABLED: 'SCHEMAS_CONTENT_FEATURE_ENABLED',
    SCHEMAS_CONTENT_VALIDATE_SCHEMA: 'SCHEMAS_CONTENT_VALIDATE_SCHEMA',
} as const;

const SCHEMAS_CONTENT_PERMISSIONS_LIST = [
    SCHEMAS_CONTENT_PERMISSIONS.SCHEMAS_CONTENT_FEATURE_ENABLED,
    SCHEMAS_CONTENT_PERMISSIONS.SCHEMAS_CONTENT_VALIDATE_SCHEMA,
] as const;

const SCHEMAS_CONTENT_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable Schemas Content Feature',
        permission: SCHEMAS_CONTENT_PERMISSIONS.SCHEMAS_CONTENT_FEATURE_ENABLED,
    },
    {
        label: 'Validate Schemas Content',
        permission: SCHEMAS_CONTENT_PERMISSIONS.SCHEMAS_CONTENT_VALIDATE_SCHEMA,
    },
];

const SchemasContentPermissions = {
    SCHEMAS_CONTENT_PERMISSIONS,
    SCHEMAS_CONTENT_PERMISSIONS_LIST,
    SCHEMAS_CONTENT_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { SchemasContentPermissions };
