import { PermissionLabel } from '..';

const SCHEMAS_DEFINITION_PERMISSIONS = {
    SCHEMAS_DEFINITION_FEATURE_ENABLED: 'SCHEMAS_DEFINITION_FEATURE_ENABLED',
    SCHEMAS_DEFINITION_VALIDATE_SCHEMA: 'SCHEMAS_DEFINITION_VALIDATE_SCHEMA',
} as const;

const SCHEMAS_DEFINITION_PERMISSIONS_LIST = [
    SCHEMAS_DEFINITION_PERMISSIONS.SCHEMAS_DEFINITION_FEATURE_ENABLED,
    SCHEMAS_DEFINITION_PERMISSIONS.SCHEMAS_DEFINITION_VALIDATE_SCHEMA,
] as const;

const SCHEMAS_DEFINITION_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable Schemas Definition Feature',
        permission:
            SCHEMAS_DEFINITION_PERMISSIONS.SCHEMAS_DEFINITION_FEATURE_ENABLED,
    },
    {
        label: 'Validate Schemas Definition',
        permission:
            SCHEMAS_DEFINITION_PERMISSIONS.SCHEMAS_DEFINITION_VALIDATE_SCHEMA,
    },
];

const SchemasDefinitionPermissions = {
    SCHEMAS_DEFINITION_PERMISSIONS,
    SCHEMAS_DEFINITION_PERMISSIONS_LIST,
    SCHEMAS_DEFINITION_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { SchemasDefinitionPermissions };
