const dataMaskingTypes = {
    GET_ALL_DATA_MASKINGS: 'GET_ALL_DATA_MASKINGS',
    GET_ALL_DATA_MASKINGS_PENDING: 'GET_ALL_DATA_MASKINGS_PENDING',
    GET_ALL_DATA_MASKINGS_FULFILLED: 'GET_ALL_DATA_MASKINGS_FULFILLED',
    GET_ALL_DATA_MASKINGS_REJECTED: 'GET_ALL_DATA_MASKINGS_REJECTED',

    CREATE_DATA_MASKING: 'CREATE_DATA_MASKING',
    CREATE_DATA_MASKING_PENDING: 'CREATE_DATA_MASKING_PENDING',
    CREATE_DATA_MASKING_FULFILLED: 'CREATE_DATA_MASKING_FULFILLED',
    CREATE_DATA_MASKING_REJECTED: 'CREATE_DATA_MASKING_REJECTED',

    DELETE_DATA_MASKING: 'DELETE_DATA_MASKING',
    DELETE_DATA_MASKING_PENDING: 'DELETE_DATA_MASKING_PENDING',
    DELETE_DATA_MASKING_FULFILLED: 'DELETE_DATA_MASKING_FULFILLED',
    DELETE_DATA_MASKING_REJECTED: 'DELETE_DATA_MASKING_REJECTED',

    EDIT_DATA_MASKING: 'EDIT_DATA_MASKING',
    EDIT_DATA_MASKING_PENDING: 'EDIT_DATA_MASKING_PENDING',
    EDIT_DATA_MASKING_FULFILLED: 'EDIT_DATA_MASKING_FULFILLED',
    EDIT_DATA_MASKING_REJECTED: 'EDIT_DATA_MASKING_REJECTED',
};

export default dataMaskingTypes;
