import AlterConsumerGroupOffsetsLineComponent from './AlterConsumerGroupOffsetsLineComponent';

const AlterConsumerGroupOffsetsLine = AlterConsumerGroupOffsetsLineComponent;

export default AlterConsumerGroupOffsetsLine;
