import BlazingConsumerRecordPreviewComponent from './BlazingConsumerRecordPreviewComponent';

const BlazingConsumerRecordPreview = BlazingConsumerRecordPreviewComponent;

export default BlazingConsumerRecordPreview;
