const auditLogTypes = {
    SEARCH_AUDIT_LOG: 'SEARCH_AUDIT_LOG',
    SEARCH_AUDIT_LOG_PENDING: 'SEARCH_AUDIT_LOG_PENDING',
    SEARCH_AUDIT_LOG_FULFILLED: 'SEARCH_AUDIT_LOG_FULFILLED',
    SEARCH_AUDIT_LOG_REJECTED: 'SEARCH_AUDIT_LOG_REJECTED',

    CLEAR_AUDIT_LOG: 'CLEAR_AUDIT_LOG',
};

export default auditLogTypes;
