openapi: 3.0.0
info:
  description: KsqlDb Query Api Documentation
  version: 0.1.0
  title: KsqlDb Query Api Documentation
tags:
  - name: KsqlDb Query
servers:
  - url: http://localhost:8080

paths:
  # Get All KsqlDb Queries
  /v1/ksqldbs/queries:
    get:
      tags:
        - KsqlDb Query
      summary: Get All KsqlDb Queries
      operationId: getAllKsqlDbQueries
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/KsqlDbQueryApiResponse"

components:
  schemas:
    # Requests

    # Responses
    KsqlDbQueryApiResponse:
      type: object
      properties:
        queryType:
          type: string
        id:
          type: string
        sql:
          type: string
        sink:
          type: string
        sinkTopic:
          type: string

    # Common
    CommonMap:
      type: object
      additionalProperties:
        type: object
    NotBlankString:
      type: string
      pattern: ^(?!\s*$).+
