openapi: 3.0.0
info:
  description: KsqlDb Table Api Documentation
  version: 0.1.0
  title: KsqlDb Table Api Documentation
tags:
  - name: KsqlDb Table
servers:
  - url: http://localhost:8080

paths:
  # Get All KsqlDb Tables
  /v1/ksqldbs/tables:
    get:
      tags:
        - KsqlDb Table
      summary: Get All KsqlDb Tables
      operationId: getAllKsqlDbTables
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/KsqlDbTableApiResponse"

components:
  schemas:
    # Requests

    # Responses
    KsqlDbTableApiResponse:
      type: object
      properties:
        name:
          type: string
        topic:
          type: string
        format:
          type: string
        keyFormat:
          type: string
        valueFormat:
          type: string
        isWindowed:
          type: boolean

    # Common
    CommonMap:
      type: object
      additionalProperties:
        type: object
    NotBlankString:
      type: string
      pattern: ^(?!\s*$).+
