openapi: 3.0.0
info:
  description: KsqlDb Connector Api Documentation
  version: 0.1.0
  title: KsqlDb Connector Api Documentation
tags:
  - name: KsqlDb Connector
servers:
  - url: http://localhost:8080

paths:
  # Get All KsqlDb Connectors
  /v1/ksqldbs/connectors:
    get:
      tags:
        - KsqlDb Connector
      summary: Get All KsqlDb Connectors
      operationId: getAllKsqlDbConnectors
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/KsqlDbConnectorApiResponse"
    post:
      tags:
        - KsqlDb Connector
      summary: Create KsqlDb Connector
      operationId: createKsqlDbConnector
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/KsqlDbConnectorCreateApiRequest"
      responses:
        204:
          description: CREATED

  # Delete KsqlDb Connector
  /v1/ksqldbs/connectors/{connectorName}:
    delete:
      tags:
        - KsqlDb Connector
      summary: Delete KsqlDb Connectors
      operationId: deleteKsqlDbConnector
      parameters:
        - name: connectorName
          in: path
          description: KsqlDb Connector name
          required: true
          schema:
            type: string
      responses:
        204:
          description: DELETED
          
components:
  schemas:
    # Requests
    KsqlDbConnectorCreateApiRequest:
      type: object
      properties:
        connectorName:
          type: string
        isSource:
          type: boolean
        properties:
          $ref: "#/components/schemas/CommonMap"

    # Responses
    KsqlDbConnectorApiResponse:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        className:
          type: string
        state:
          type: string

    # Common
    CommonMap:
      type: object
      additionalProperties:
        type: object
    NotBlankString:
      type: string
      pattern: ^(?!\s*$).+
