import ClearConsumerGroupOffsetsLineComponent from './ClearConsumerGroupOffsetsLineComponent';

const ClearConsumerGroupOffsetsLine = ClearConsumerGroupOffsetsLineComponent;

export default ClearConsumerGroupOffsetsLine;
