const serverPermissionsTypes = {
    GET_SERVER_PERMISSIONS: 'GET_SERVER_PERMISSIONS',
    GET_SERVER_PERMISSIONS_PENDING: 'GET_SERVER_PERMISSIONS_PENDING',
    GET_SERVER_PERMISSIONS_FULFILLED: 'GET_SERVER_PERMISSIONS_FULFILLED',
    GET_SERVER_PERMISSIONS_REJECTED: 'GET_SERVER_PERMISSIONS_REJECTED',

    EDIT_SERVER_PERMISSIONS: 'EDIT_SERVER_PERMISSIONS',
    EDIT_SERVER_PERMISSIONS_PENDING: 'EDIT_SERVER_PERMISSIONS_PENDING',
    EDIT_SERVER_PERMISSIONS_FULFILLED: 'EDIT_SERVER_PERMISSIONS_FULFILLED',
    EDIT_SERVER_PERMISSIONS_REJECTED: 'EDIT_SERVER_PERMISSIONS_REJECTED',
};

export default serverPermissionsTypes;
