import { PermissionLabel } from '..';

const SCHEMA_REGISTRY_SERVER_PERMISSIONS = {
    UPDATE_SCHEMA_REGISTRY_COMPATIBILITY:
        'UPDATE_SCHEMA_REGISTRY_COMPATIBILITY',
    UPDATE_SCHEMA_REGISTRY_MODE: 'UPDATE_SCHEMA_REGISTRY_MODE',
} as const;

const SCHEMA_REGISTRY_SERVER_PERMISSIONS_LIST = [
    SCHEMA_REGISTRY_SERVER_PERMISSIONS.UPDATE_SCHEMA_REGISTRY_COMPATIBILITY,
    SCHEMA_REGISTRY_SERVER_PERMISSIONS.UPDATE_SCHEMA_REGISTRY_MODE,
] as const;

const SCHEMA_REGISTRY_SERVER_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] =
    [
        {
            label: 'Update Schema Registry Compatibility',
            permission:
                SCHEMA_REGISTRY_SERVER_PERMISSIONS.UPDATE_SCHEMA_REGISTRY_COMPATIBILITY,
        },
        {
            label: 'Update Schema Registry Mode',
            permission:
                SCHEMA_REGISTRY_SERVER_PERMISSIONS.UPDATE_SCHEMA_REGISTRY_MODE,
        },
    ];

const SchemaRegistryServerPermissions = {
    SCHEMA_REGISTRY_SERVER_PERMISSIONS,
    SCHEMA_REGISTRY_SERVER_PERMISSIONS_LIST,
    SCHEMA_REGISTRY_SERVER_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { SchemaRegistryServerPermissions };
