import { PermissionLabel } from '..';

const SCHEMA_REGISTRY_DASHBOARD_PERMISSIONS = {
    SCHEMA_REGISTRY_DASHBOARD_FEATURE_ENABLED:
        'SCHEMA_REGISTRY_DASHBOARD_FEATURE_ENABLED',
    VIEW_SCHEMA_REGISTRY_DASHBOARD: 'VIEW_SCHEMA_REGISTRY_DASHBOARD',
} as const;

const SCHEMA_REGISTRY_DASHBOARD_PERMISSIONS_LIST = [
    SCHEMA_REGISTRY_DASHBOARD_PERMISSIONS.SCHEMA_REGISTRY_DASHBOARD_FEATURE_ENABLED,
    SCHEMA_REGISTRY_DASHBOARD_PERMISSIONS.VIEW_SCHEMA_REGISTRY_DASHBOARD,
] as const;

const SCHEMA_REGISTRY_DASHBOARD_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] =
    [
        {
            label: 'Enable Schema Registry Dashboard Feature',
            permission:
                SCHEMA_REGISTRY_DASHBOARD_PERMISSIONS.SCHEMA_REGISTRY_DASHBOARD_FEATURE_ENABLED,
        },
        {
            label: 'View Dashboard',
            permission:
                SCHEMA_REGISTRY_DASHBOARD_PERMISSIONS.VIEW_SCHEMA_REGISTRY_DASHBOARD,
        },
    ];

const SchemaRegistryDashboardPermissions = {
    SCHEMA_REGISTRY_DASHBOARD_PERMISSIONS,
    SCHEMA_REGISTRY_DASHBOARD_PERMISSIONS_LIST,
    SCHEMA_REGISTRY_DASHBOARD_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { SchemaRegistryDashboardPermissions };
