import BlazingProducerRecordPreviewComponent from './BlazingProducerRecordPreviewComponent';

const BlazingProducerRecordPreview = BlazingProducerRecordPreviewComponent;

export default BlazingProducerRecordPreview;
