import AllKsqlDbQueriesBodySqlDetailsComponent from './AllKsqlDbQueriesBodySqlDetailsComponent';

const AllKsqlDbQueriesBodySqlDetails = AllKsqlDbQueriesBodySqlDetailsComponent;

export default AllKsqlDbQueriesBodySqlDetails;
