const userTypes = {
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_USERS_PENDING: 'GET_ALL_USERS_PENDING',
    GET_ALL_USERS_FULFILLED: 'GET_ALL_USERS_FULFILLED',
    GET_ALL_USERS_REJECTED: 'GET_ALL_USERS_REJECTED',

    CREATE_USER: 'CREATE_USER',
    CREATE_USER_PENDING: 'CREATE_USER_PENDING',
    CREATE_USER_FULFILLED: 'CREATE_USER_FULFILLED',
    CREATE_USER_REJECTED: 'CREATE_USER_REJECTED',

    DELETE_USER: 'DELETE_USER',
    DELETE_USER_PENDING: 'DELETE_USER_PENDING',
    DELETE_USER_FULFILLED: 'DELETE_USER_FULFILLED',
    DELETE_USER_REJECTED: 'DELETE_USER_REJECTED',

    EDIT_USER: 'EDIT_USER',
    EDIT_USER_PENDING: 'EDIT_USER_PENDING',
    EDIT_USER_FULFILLED: 'EDIT_USER_FULFILLED',
    EDIT_USER_REJECTED: 'EDIT_USER_REJECTED',

    EDIT_USER_PASSWORD: 'EDIT_USER_PASSWORD',
    EDIT_USER_PASSWORD_PENDING: 'EDIT_USER_PASSWORD_PENDING',
    EDIT_USER_PASSWORD_FULFILLED: 'EDIT_USER_PASSWORD_FULFILLED',
    EDIT_USER_PASSWORD_REJECTED: 'EDIT_USER_PASSWORD_REJECTED',

    EDIT_USER_PASSWORD_WITHOUT_CURRENT: 'EDIT_USER_PASSWORD_WITHOUT_CURRENT',
    EDIT_USER_PASSWORD_WITHOUT_CURRENT_PENDING:
        'EDIT_USER_PASSWORD_WITHOUT_CURRENT_PENDING',
    EDIT_USER_PASSWORD_WITHOUT_CURRENT_FULFILLED:
        'EDIT_USER_PASSWORD_WITHOUT_CURRENT_FULFILLED',
    EDIT_USER_PASSWORD_WITHOUT_CURRENT_REJECTED:
        'EDIT_USER_PASSWORD_WITHOUT_CURRENT_REJECTED',

    GET_USER_DETAILS: 'GET_USER_DETAILS',
    GET_USER_DETAILS_PENDING: 'GET_USER_DETAILS_PENDING',
    GET_USER_DETAILS_FULFILLED: 'GET_USER_DETAILS_FULFILLED',
    GET_USER_DETAILS_REJECTED: 'GET_USER_DETAILS_REJECTED',
};

export default userTypes;
