import { PermissionLabel } from '..';

const DATA_MASKING_PERMISSIONS = {
    DATA_MASKING_FEATURE_ENABLED: 'DATA_MASKING_FEATURE_ENABLED',
    DESCRIBE_DATA_MASKINGS: 'DESCRIBE_DATA_MASKINGS',
    CREATE_DATA_MASKING: 'CREATE_DATA_MASKING',
    EXPORT_DATA_MASKINGS: 'EXPORT_DATA_MASKINGS',
    IMPORT_DATA_MASKINGS: 'IMPORT_DATA_MASKINGS',
    EDIT_DATA_MASKING: 'EDIT_DATA_MASKING',
    DELETE_DATA_MASKING: 'DELETE_DATA_MASKING',
} as const;

const DATA_MASKING_PERMISSIONS_LIST = [
    DATA_MASKING_PERMISSIONS.DATA_MASKING_FEATURE_ENABLED,
    DATA_MASKING_PERMISSIONS.DESCRIBE_DATA_MASKINGS,
    DATA_MASKING_PERMISSIONS.CREATE_DATA_MASKING,
    DATA_MASKING_PERMISSIONS.EXPORT_DATA_MASKINGS,
    DATA_MASKING_PERMISSIONS.IMPORT_DATA_MASKINGS,
    DATA_MASKING_PERMISSIONS.EDIT_DATA_MASKING,
    DATA_MASKING_PERMISSIONS.DELETE_DATA_MASKING,
] as const;

const DATA_MASKING_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable Data Masking Feature',
        permission: DATA_MASKING_PERMISSIONS.DATA_MASKING_FEATURE_ENABLED,
    },
    {
        label: 'Describe Data Masking Rules',
        permission: DATA_MASKING_PERMISSIONS.DESCRIBE_DATA_MASKINGS,
    },
    {
        label: 'Create Data Masking Rule',
        permission: DATA_MASKING_PERMISSIONS.CREATE_DATA_MASKING,
    },
    {
        label: 'Export Data Masking Rules',
        permission: DATA_MASKING_PERMISSIONS.EXPORT_DATA_MASKINGS,
    },
    {
        label: 'Import Data Masking Rules',
        permission: DATA_MASKING_PERMISSIONS.IMPORT_DATA_MASKINGS,
    },
    {
        label: 'Edit Data Masking Rule',
        permission: DATA_MASKING_PERMISSIONS.EDIT_DATA_MASKING,
    },
    {
        label: 'Delete Data Masking Rule',
        permission: DATA_MASKING_PERMISSIONS.DELETE_DATA_MASKING,
    },
];

const DataMaskingPermissions = {
    DATA_MASKING_PERMISSIONS,
    DATA_MASKING_PERMISSIONS_LIST,
    DATA_MASKING_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { DataMaskingPermissions };
