import { PermissionLabel } from '..';

const MANAGEMENT_CLUSTER_PERMISSIONS = {
    MANAGEMENT_CLUSTER_FEATURE_ENABLED: 'MANAGEMENT_CLUSTER_FEATURE_ENABLED',
    MANAGEMENT_DESCRIBE_CLUSTERS: 'MANAGEMENT_DESCRIBE_CLUSTERS',
    MANAGEMENT_CREATE_CLUSTER: 'MANAGEMENT_CREATE_CLUSTER',
    MANAGEMENT_TEST_CLUSTER_CONNECTIVITY:
        'MANAGEMENT_TEST_CLUSTER_CONNECTIVITY',
    MANAGEMENT_EXPORT_CLUSTER: 'MANAGEMENT_EXPORT_CLUSTER',
    MANAGEMENT_IMPORT_CLUSTER: 'MANAGEMENT_IMPORT_CLUSTER',
    MANAGEMENT_EDIT_CLUSTER: 'MANAGEMENT_EDIT_CLUSTER',
    MANAGEMENT_DELETE_CLUSTER: 'MANAGEMENT_DELETE_CLUSTER',
} as const;

const MANAGEMENT_CLUSTER_PERMISSIONS_LIST = [
    MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_CLUSTER_FEATURE_ENABLED,
    MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_DESCRIBE_CLUSTERS,
    MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_CREATE_CLUSTER,
    MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_TEST_CLUSTER_CONNECTIVITY,
    MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_EXPORT_CLUSTER,
    MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_IMPORT_CLUSTER,
    MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_EDIT_CLUSTER,
    MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_DELETE_CLUSTER,
] as const;

const MANAGEMENT_CLUSTER_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable Clusters Feature',
        permission:
            MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_CLUSTER_FEATURE_ENABLED,
    },
    {
        label: 'Describe Clusters',
        permission: MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_DESCRIBE_CLUSTERS,
    },
    {
        label: 'Create Cluster',
        permission: MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_CREATE_CLUSTER,
    },
    {
        label: 'Test Cluster Connectivity',
        permission:
            MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_TEST_CLUSTER_CONNECTIVITY,
    },
    {
        label: 'Export Cluster',
        permission: MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_EXPORT_CLUSTER,
    },
    {
        label: 'Import Cluster',
        permission: MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_IMPORT_CLUSTER,
    },
    {
        label: 'Edit Cluster',
        permission: MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_EDIT_CLUSTER,
    },
    {
        label: 'Delete Cluster',
        permission: MANAGEMENT_CLUSTER_PERMISSIONS.MANAGEMENT_DELETE_CLUSTER,
    },
];

const ManagementClusterPermissions = {
    MANAGEMENT_CLUSTER_PERMISSIONS,
    MANAGEMENT_CLUSTER_PERMISSIONS_LIST,
    MANAGEMENT_CLUSTER_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { ManagementClusterPermissions };
