import { PermissionLabel } from '..';

const MANAGEMENT_KAFKA_CONNECT_PERMISSIONS = {
    MANAGEMENT_KAFKA_CONNECT_FEATURE_ENABLED:
        'MANAGEMENT_KAFKA_CONNECT_FEATURE_ENABLED',
    MANAGEMENT_DESCRIBE_KAFKA_CONNECTS: 'MANAGEMENT_DESCRIBE_KAFKA_CONNECTS',
    MANAGEMENT_CREATE_KAFKA_CONNECT: 'MANAGEMENT_CREATE_KAFKA_CONNECT',
    MANAGEMENT_TEST_KAFKA_CONNECT_CONNECTIVITY:
        'MANAGEMENT_TEST_KAFKA_CONNECT_CONNECTIVITY',
    MANAGEMENT_EXPORT_KAFKA_CONNECT: 'MANAGEMENT_EXPORT_KAFKA_CONNECT',
    MANAGEMENT_IMPORT_KAFKA_CONNECT: 'MANAGEMENT_IMPORT_KAFKA_CONNECT',
    MANAGEMENT_EDIT_KAFKA_CONNECT: 'MANAGEMENT_EDIT_KAFKA_CONNECT',
    MANAGEMENT_DELETE_KAFKA_CONNECT: 'MANAGEMENT_DELETE_KAFKA_CONNECT',
} as const;

const MANAGEMENT_KAFKA_CONNECT_PERMISSIONS_LIST = [
    MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_KAFKA_CONNECT_FEATURE_ENABLED,
    MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_DESCRIBE_KAFKA_CONNECTS,
    MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_CREATE_KAFKA_CONNECT,
    MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_TEST_KAFKA_CONNECT_CONNECTIVITY,
    MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_EXPORT_KAFKA_CONNECT,
    MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_IMPORT_KAFKA_CONNECT,
    MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_EDIT_KAFKA_CONNECT,
    MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_DELETE_KAFKA_CONNECT,
] as const;

const MANAGEMENT_KAFKA_CONNECT_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] =
    [
        {
            label: 'Enable Kafka Connects Feature',
            permission:
                MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_KAFKA_CONNECT_FEATURE_ENABLED,
        },
        {
            label: 'Describe Kafka Connects',
            permission:
                MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_DESCRIBE_KAFKA_CONNECTS,
        },
        {
            label: 'Create Kafka Connect',
            permission:
                MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_CREATE_KAFKA_CONNECT,
        },
        {
            label: 'Test Kafka Connect Connectivity',
            permission:
                MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_TEST_KAFKA_CONNECT_CONNECTIVITY,
        },
        {
            label: 'Export Kafka Connect',
            permission:
                MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_EXPORT_KAFKA_CONNECT,
        },
        {
            label: 'Import Kafka Connect',
            permission:
                MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_IMPORT_KAFKA_CONNECT,
        },
        {
            label: 'Edit Kafka Connect',
            permission:
                MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_EDIT_KAFKA_CONNECT,
        },
        {
            label: 'Delete Kafka Connect',
            permission:
                MANAGEMENT_KAFKA_CONNECT_PERMISSIONS.MANAGEMENT_DELETE_KAFKA_CONNECT,
        },
    ];

const ManagementKafkaConnectPermissions = {
    MANAGEMENT_KAFKA_CONNECT_PERMISSIONS,
    MANAGEMENT_KAFKA_CONNECT_PERMISSIONS_LIST,
    MANAGEMENT_KAFKA_CONNECT_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { ManagementKafkaConnectPermissions };
