import { PermissionLabel } from '..';

const MANAGEMENT_KSQLDB_PERMISSIONS = {
    MANAGEMENT_KSQLDB_FEATURE_ENABLED: 'MANAGEMENT_KSQLDB_FEATURE_ENABLED',
    MANAGEMENT_DESCRIBE_KSQLDBS: 'MANAGEMENT_DESCRIBE_KSQLDBS',
    MANAGEMENT_CREATE_KSQLDB: 'MANAGEMENT_CREATE_KSQLDB',
    MANAGEMENT_TEST_KSQLDB_CONNECTIVITY: 'MANAGEMENT_TEST_KSQLDB_CONNECTIVITY',
    MANAGEMENT_EXPORT_KSQLDB: 'MANAGEMENT_EXPORT_KSQLDB',
    MANAGEMENT_IMPORT_KSQLDB: 'MANAGEMENT_IMPORT_KSQLDB',
    MANAGEMENT_EDIT_KSQLDB: 'MANAGEMENT_EDIT_KSQLDB',
    MANAGEMENT_DELETE_KSQLDB: 'MANAGEMENT_DELETE_KSQLDB',
} as const;

const MANAGEMENT_KSQLDB_PERMISSIONS_LIST = [
    MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_KSQLDB_FEATURE_ENABLED,
    MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_DESCRIBE_KSQLDBS,
    MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_CREATE_KSQLDB,
    MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_TEST_KSQLDB_CONNECTIVITY,
    MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_EXPORT_KSQLDB,
    MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_IMPORT_KSQLDB,
    MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_EDIT_KSQLDB,
    MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_DELETE_KSQLDB,
] as const;

const MANAGEMENT_KSQLDB_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable KsqlDbs Feature',
        permission:
            MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_KSQLDB_FEATURE_ENABLED,
    },
    {
        label: 'Describe KsqlDbs',
        permission: MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_DESCRIBE_KSQLDBS,
    },
    {
        label: 'Create KsqlDb',
        permission: MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_CREATE_KSQLDB,
    },
    {
        label: 'Test KsqlDb Connectivity',
        permission:
            MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_TEST_KSQLDB_CONNECTIVITY,
    },
    {
        label: 'Export KsqlDb',
        permission: MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_EXPORT_KSQLDB,
    },
    {
        label: 'Import KsqlDb',
        permission: MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_IMPORT_KSQLDB,
    },
    {
        label: 'Edit KsqlDb',
        permission: MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_EDIT_KSQLDB,
    },
    {
        label: 'Delete KsqlDb',
        permission: MANAGEMENT_KSQLDB_PERMISSIONS.MANAGEMENT_DELETE_KSQLDB,
    },
];

const ManagementKsqlDbPermissions = {
    MANAGEMENT_KSQLDB_PERMISSIONS,
    MANAGEMENT_KSQLDB_PERMISSIONS_LIST,
    MANAGEMENT_KSQLDB_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { ManagementKsqlDbPermissions };
