import { PermissionLabel } from '..';

const MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS = {
    MANAGEMENT_SCHEMA_REGISTRY_FEATURE_ENABLED:
        'MANAGEMENT_SCHEMA_REGISTRY_FEATURE_ENABLED',
    MANAGEMENT_DESCRIBE_SCHEMA_REGISTRIES:
        'MANAGEMENT_DESCRIBE_SCHEMA_REGISTRIES',
    MANAGEMENT_CREATE_SCHEMA_REGISTRY: 'MANAGEMENT_CREATE_SCHEMA_REGISTRY',
    MANAGEMENT_TEST_SCHEMA_REGISTRY_CONNECTIVITY:
        'MANAGEMENT_TEST_SCHEMA_REGISTRY_CONNECTIVITY',
    MANAGEMENT_EXPORT_SCHEMA_REGISTRY: 'MANAGEMENT_EXPORT_SCHEMA_REGISTRY',
    MANAGEMENT_IMPORT_SCHEMA_REGISTRY: 'MANAGEMENT_IMPORT_SCHEMA_REGISTRY',
    MANAGEMENT_EDIT_SCHEMA_REGISTRY: 'MANAGEMENT_EDIT_SCHEMA_REGISTRY',
    MANAGEMENT_DELETE_SCHEMA_REGISTRY: 'MANAGEMENT_DELETE_SCHEMA_REGISTRY',
} as const;

const MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS_LIST = [
    MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_SCHEMA_REGISTRY_FEATURE_ENABLED,
    MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_DESCRIBE_SCHEMA_REGISTRIES,
    MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_CREATE_SCHEMA_REGISTRY,
    MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_TEST_SCHEMA_REGISTRY_CONNECTIVITY,
    MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_EXPORT_SCHEMA_REGISTRY,
    MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_IMPORT_SCHEMA_REGISTRY,
    MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_EDIT_SCHEMA_REGISTRY,
    MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_DELETE_SCHEMA_REGISTRY,
] as const;

const MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] =
    [
        {
            label: 'Enable Schema Registries Feature',
            permission:
                MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_SCHEMA_REGISTRY_FEATURE_ENABLED,
        },
        {
            label: 'Describe Schema Registries',
            permission:
                MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_DESCRIBE_SCHEMA_REGISTRIES,
        },
        {
            label: 'Create Schema Registry',
            permission:
                MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_CREATE_SCHEMA_REGISTRY,
        },
        {
            label: 'Test Schema Registry Connectivity',
            permission:
                MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_TEST_SCHEMA_REGISTRY_CONNECTIVITY,
        },
        {
            label: 'Export Schema Registry',
            permission:
                MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_EXPORT_SCHEMA_REGISTRY,
        },
        {
            label: 'Import Schema Registry',
            permission:
                MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_IMPORT_SCHEMA_REGISTRY,
        },
        {
            label: 'Edit Schema Registry',
            permission:
                MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_EDIT_SCHEMA_REGISTRY,
        },
        {
            label: 'Delete Schema Registry',
            permission:
                MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS.MANAGEMENT_DELETE_SCHEMA_REGISTRY,
        },
    ];

const ManagementSchemaRegistryPermissions = {
    MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS,
    MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS_LIST,
    MANAGEMENT_SCHEMA_REGISTRY_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { ManagementSchemaRegistryPermissions };
