import { PermissionLabel } from '..';

const OIDC_PROVIDER_PERMISSIONS = {
    OIDC_PROVIDER_FEATURE_ENABLED: 'OIDC_PROVIDER_FEATURE_ENABLED',
    DESCRIBE_OIDC_PROVIDERS: 'DESCRIBE_OIDC_PROVIDERS',
    CREATE_OIDC_PROVIDER: 'CREATE_OIDC_PROVIDER',
    TEST_OIDC_PROVIDER_CONFIGURATION: 'TEST_OIDC_PROVIDER_CONFIGURATION',
    EDIT_OIDC_PROVIDER: 'EDIT_OIDC_PROVIDER',
    DELETE_OIDC_PROVIDER: 'DELETE_OIDC_PROVIDER',
} as const;

const OIDC_PROVIDER_PERMISSIONS_LIST = [
    OIDC_PROVIDER_PERMISSIONS.OIDC_PROVIDER_FEATURE_ENABLED,
    OIDC_PROVIDER_PERMISSIONS.DESCRIBE_OIDC_PROVIDERS,
    OIDC_PROVIDER_PERMISSIONS.CREATE_OIDC_PROVIDER,
    OIDC_PROVIDER_PERMISSIONS.TEST_OIDC_PROVIDER_CONFIGURATION,
    OIDC_PROVIDER_PERMISSIONS.EDIT_OIDC_PROVIDER,
    OIDC_PROVIDER_PERMISSIONS.DELETE_OIDC_PROVIDER,
] as const;

const OIDC_PROVIDER_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable OpenID Connect Providers Feature',
        permission: OIDC_PROVIDER_PERMISSIONS.OIDC_PROVIDER_FEATURE_ENABLED,
    },
    {
        label: 'Describe OpenID Connect Providers',
        permission: OIDC_PROVIDER_PERMISSIONS.DESCRIBE_OIDC_PROVIDERS,
    },
    {
        label: 'Create OpenID Connect Provider',
        permission: OIDC_PROVIDER_PERMISSIONS.CREATE_OIDC_PROVIDER,
    },
    {
        label: 'Test OpenID Connect Provider Configuration',
        permission: OIDC_PROVIDER_PERMISSIONS.TEST_OIDC_PROVIDER_CONFIGURATION,
    },
    {
        label: 'Edit OpenID Connect Provider',
        permission: OIDC_PROVIDER_PERMISSIONS.EDIT_OIDC_PROVIDER,
    },
    {
        label: 'Delete OpenID Connect Provider',
        permission: OIDC_PROVIDER_PERMISSIONS.DELETE_OIDC_PROVIDER,
    },
];

const OIDCProviderPermissions = {
    OIDC_PROVIDER_PERMISSIONS,
    OIDC_PROVIDER_PERMISSIONS_LIST,
    OIDC_PROVIDER_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { OIDCProviderPermissions };
