import { PermissionLabel } from '..';

const SERVER_PERMISSIONS = {
    SERVER_PERMISSIONS_FEATURE_ENABLED: 'SERVER_PERMISSIONS_FEATURE_ENABLED',
    DESCRIBE_SERVER_PERMISSIONS: 'DESCRIBE_SERVER_PERMISSIONS',
    EDIT_SERVER_PERMISSIONS: 'EDIT_SERVER_PERMISSIONS',
} as const;

const SERVER_PERMISSIONS_LIST = [
    SERVER_PERMISSIONS.SERVER_PERMISSIONS_FEATURE_ENABLED,
    SERVER_PERMISSIONS.DESCRIBE_SERVER_PERMISSIONS,
    SERVER_PERMISSIONS.EDIT_SERVER_PERMISSIONS,
] as const;

const SERVER_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable Server Permissions Feature',
        permission: SERVER_PERMISSIONS.SERVER_PERMISSIONS_FEATURE_ENABLED,
    },
    {
        label: 'Describe Server Permissions',
        permission: SERVER_PERMISSIONS.DESCRIBE_SERVER_PERMISSIONS,
    },
    {
        label: 'Edit Server Permissions',
        permission: SERVER_PERMISSIONS.EDIT_SERVER_PERMISSIONS,
    },
];

const ServerPermissions = {
    SERVER_PERMISSIONS,
    SERVER_PERMISSIONS_LIST,
    SERVER_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { ServerPermissions };
