const OIDCProviderTypes = {
    GET_ALL_OIDC_PROVIDERS: 'GET_ALL_OIDC_PROVIDERS',
    GET_ALL_OIDC_PROVIDERS_PENDING: 'GET_ALL_OIDC_PROVIDERS_PENDING',
    GET_ALL_OIDC_PROVIDERS_FULFILLED: 'GET_ALL_OIDC_PROVIDERS_FULFILLED',
    GET_ALL_OIDC_PROVIDERS_REJECTED: 'GET_ALL_OIDC_PROVIDERS_REJECTED',

    CREATE_OIDC_PROVIDER: 'CREATE_OIDC_PROVIDER',
    CREATE_OIDC_PROVIDER_PENDING: 'CREATE_OIDC_PROVIDER_PENDING',
    CREATE_OIDC_PROVIDER_FULFILLED: 'CREATE_OIDC_PROVIDER_FULFILLED',
    CREATE_OIDC_PROVIDER_REJECTED: 'CREATE_OIDC_PROVIDER_REJECTED',

    DELETE_OIDC_PROVIDER: 'DELETE_OIDC_PROVIDER',
    DELETE_OIDC_PROVIDER_PENDING: 'DELETE_OIDC_PROVIDER_PENDING',
    DELETE_OIDC_PROVIDER_FULFILLED: 'DELETE_OIDC_PROVIDER_FULFILLED',
    DELETE_OIDC_PROVIDER_REJECTED: 'DELETE_OIDC_PROVIDER_REJECTED',

    EDIT_OIDC_PROVIDER: 'EDIT_OIDC_PROVIDER',
    EDIT_OIDC_PROVIDER_PENDING: 'EDIT_OIDC_PROVIDER_PENDING',
    EDIT_OIDC_PROVIDER_FULFILLED: 'EDIT_OIDC_PROVIDER_FULFILLED',
    EDIT_OIDC_PROVIDER_REJECTED: 'EDIT_OIDC_PROVIDER_REJECTED',

    GET_OIDC_PROVIDER_DETAILS: 'GET_OIDC_PROVIDER_DETAILS',
    GET_OIDC_PROVIDER_DETAILS_PENDING: 'GET_OIDC_PROVIDER_DETAILS_PENDING',
    GET_OIDC_PROVIDER_DETAILS_FULFILLED: 'GET_OIDC_PROVIDER_DETAILS_FULFILLED',
    GET_OIDC_PROVIDER_DETAILS_REJECTED: 'GET_OIDC_PROVIDER_DETAILS_REJECTED',

    GET_OIDC_PROVIDER_WELL_KNOWN_CONFIGURATION:
        'GET_OIDC_PROVIDER_WELL_KNOWN_CONFIGURATION',
    GET_OIDC_PROVIDER_WELL_KNOWN_CONFIGURATION_PENDING:
        'GET_OIDC_PROVIDER_WELL_KNOWN_CONFIGURATION_PENDING',
    GET_OIDC_PROVIDER_WELL_KNOWN_CONFIGURATION_FULFILLED:
        'GET_OIDC_PROVIDER_WELL_KNOWN_CONFIGURATION_FULFILLED',
    GET_OIDC_PROVIDER_WELL_KNOWN_CONFIGURATION_REJECTED:
        'GET_OIDC_PROVIDER_WELL_KNOWN_CONFIGURATION_REJECTED',

    TEST_OIDC_PROVIDER_BROWSER_CONNECTIVITY:
        'TEST_OIDC_PROVIDER_BROWSER_CONNECTIVITY',
    TEST_OIDC_PROVIDER_BROWSER_CONNECTIVITY_PENDING:
        'TEST_OIDC_PROVIDER_BROWSER_CONNECTIVITY_PENDING',
    TEST_OIDC_PROVIDER_BROWSER_CONNECTIVITY_FULFILLED:
        'TEST_OIDC_PROVIDER_BROWSER_CONNECTIVITY_FULFILLED',
    TEST_OIDC_PROVIDER_BROWSER_CONNECTIVITY_REJECTED:
        'TEST_OIDC_PROVIDER_BROWSER_CONNECTIVITY_REJECTED',

    TEST_OIDC_PROVIDER_SERVER_CONNECTIVITY:
        'TEST_OIDC_PROVIDER_SERVER_CONNECTIVITY',
    TEST_OIDC_PROVIDER_SERVER_CONNECTIVITY_PENDING:
        'TEST_OIDC_PROVIDER_SERVER_CONNECTIVITY_PENDING',
    TEST_OIDC_PROVIDER_SERVER_CONNECTIVITY_FULFILLED:
        'TEST_OIDC_PROVIDER_SERVER_CONNECTIVITY_FULFILLED',
    TEST_OIDC_PROVIDER_SERVER_CONNECTIVITY_REJECTED:
        'TEST_OIDC_PROVIDER_SERVER_CONNECTIVITY_REJECTED',
};

export default OIDCProviderTypes;
