#spring:
#  jpa:
##    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

BLAZINGKRAFT_DATASOURCE_TYPE: H2

BLAZINGKRAFT_DATASOURCE_POSTGRESQL_URL: jdbc:postgresql://localhost:5432/blazingkraft
BLAZINGKRAFT_DATASOURCE_POSTGRESQL_USERNAME: postgres
BLAZINGKRAFT_DATASOURCE_POSTGRESQL_PASSWORD: postgres

BLAZINGKRAFT_DATASOURCE_MYSQL_URL: jdbc:mysql://localhost:3306/blazingkraft
BLAZINGKRAFT_DATASOURCE_MYSQL_USERNAME: root
BLAZINGKRAFT_DATASOURCE_MYSQL_PASSWORD: mysql

BLAZINGKRAFT_DATASOURCE_MARIADB_URL: jdbc:mariadb://localhost:3306/blazingkraft
BLAZINGKRAFT_DATASOURCE_MARIADB_USERNAME: root
BLAZINGKRAFT_DATASOURCE_MARIADB_PASSWORD: mariadb

BLAZINGKRAFT_DATASOURCE_SQLSERVER_URL: jdbc:sqlserver://;serverName=localhost;databaseName=blazingkraft;encrypt=true;trustServerCertificate=true
BLAZINGKRAFT_DATASOURCE_SQLSERVER_USERNAME: SA
BLAZINGKRAFT_DATASOURCE_SQLSERVER_PASSWORD: SqlServer@123

BLAZINGKRAFT_AUDIT_LEVEL: ERROR


BLAZINGKRAFT_ADMIN_EMAIL: admin
BLAZINGKRAFT_ADMIN_PASSWORD: admin

BLAZINGKRAFT_OIDC_PROVIDER_CODE: InternalKeycloak
BLAZINGKRAFT_OIDC_PROVIDER_NAME: Internal Keycloak
BLAZINGKRAFT_OIDC_PROVIDER_ISSUER: http://localhost:8080/auth/realms/blazingkraft
BLAZINGKRAFT_OIDC_PROVIDER_CLIENT_ID: ui
BLAZINGKRAFT_OIDC_PROVIDER_CLIENT_SECTET: secret
BLAZINGKRAFT_OIDC_PROVIDER_PKCE_ENABLED: true
BLAZINGKRAFT_OIDC_PROVIDER_PROVIDER_TYPE: Keycloak
BLAZINGKRAFT_OIDC_PROVIDER_SCOPES: openid;;;profile;;;email;;;address;;;phone