const loginTypes = {
    LOGIN: 'LOGIN',
    LOGIN_PENDING: 'LOGIN_PENDING',
    LOGIN_FULFILLED: 'LOGIN_FULFILLED',
    LOGIN_REJECTED: 'LOGIN_REJECTED',

    REFRESH_TOKEN: 'REFRESH_TOKEN',
    REFRESH_TOKEN_PENDING: 'REFRESH_TOKEN_PENDING',
    REFRESH_TOKEN_FULFILLED: 'REFRESH_TOKEN_FULFILLED',
    REFRESH_TOKEN_REJECTED: 'REFRESH_TOKEN_REJECTED',

    OIDC_PROVIDER_REFRESH_TOKEN: 'OIDC_PROVIDER_REFRESH_TOKEN',

    OIDC_PROVIDER_SIGNIN_CALLBACK: 'OIDC_PROVIDER_SIGNIN_CALLBACK',
    OIDC_PROVIDER_SIGNIN_CALLBACK_PENDING:
        'OIDC_PROVIDER_SIGNIN_CALLBACK_PENDING',
    OIDC_PROVIDER_SIGNIN_CALLBACK_FULFILLED:
        'OIDC_PROVIDER_SIGNIN_CALLBACK_FULFILLED',
    OIDC_PROVIDER_SIGNIN_CALLBACK_REJECTED:
        'OIDC_PROVIDER_SIGNIN_CALLBACK_REJECTED',

    SET_OIDC_PROVIDER_CONNECTED_USER: 'SET_OIDC_PROVIDER_CONNECTED_USER',
};

export default loginTypes;
