const groupTypes = {
    GET_ALL_GROUPS: 'GET_ALL_GROUPS',
    GET_ALL_GROUPS_PENDING: 'GET_ALL_GROUPS_PENDING',
    GET_ALL_GROUPS_FULFILLED: 'GET_ALL_GROUPS_FULFILLED',
    GET_ALL_GROUPS_REJECTED: 'GET_ALL_GROUPS_REJECTED',

    CREATE_GROUP: 'CREATE_GROUP',
    CREATE_GROUP_PENDING: 'CREATE_GROUP_PENDING',
    CREATE_GROUP_FULFILLED: 'CREATE_GROUP_FULFILLED',
    CREATE_GROUP_REJECTED: 'CREATE_GROUP_REJECTED',

    DELETE_GROUP: 'DELETE_GROUP',
    DELETE_GROUP_PENDING: 'DELETE_GROUP_PENDING',
    DELETE_GROUP_FULFILLED: 'DELETE_GROUP_FULFILLED',
    DELETE_GROUP_REJECTED: 'DELETE_GROUP_REJECTED',

    EDIT_GROUP: 'EDIT_GROUP',
    EDIT_GROUP_PENDING: 'EDIT_GROUP_PENDING',
    EDIT_GROUP_FULFILLED: 'EDIT_GROUP_FULFILLED',
    EDIT_GROUP_REJECTED: 'EDIT_GROUP_REJECTED',

    GET_GROUP_DETAILS: 'GET_GROUP_DETAILS',
    GET_GROUP_DETAILS_PENDING: 'GET_GROUP_DETAILS_PENDING',
    GET_GROUP_DETAILS_FULFILLED: 'GET_GROUP_DETAILS_FULFILLED',
    GET_GROUP_DETAILS_REJECTED: 'GET_GROUP_DETAILS_REJECTED',
};

export default groupTypes;
