import EditConnectorValidationPreviewComponent from './EditConnectorValidationPreviewComponent';

const EditConnectorValidationPreview = EditConnectorValidationPreviewComponent;

export default EditConnectorValidationPreview;
