import { PermissionLabel } from '..';

const KSQLDB_CONNECTOR_PERMISSIONS = {
    KSQLDB_CONNECTOR_FEATURE_ENABLED: 'KSQLDB_CONNECTOR_FEATURE_ENABLED',
    DESCRIBE_KSQLDB_CONNECTORS: 'DESCRIBE_KSQLDB_CONNECTORS',
    DELETE_KSQLDB_CONNECTOR: 'DELETE_KSQLDB_CONNECTOR',
    CREATE_KSQLDB_CONNECTOR: 'CREATE_KSQLDB_CONNECTOR',
} as const;

const KSQLDB_CONNECTOR_PERMISSIONS_LIST = [
    KSQLDB_CONNECTOR_PERMISSIONS.KSQLDB_CONNECTOR_FEATURE_ENABLED,
    KSQLDB_CONNECTOR_PERMISSIONS.DESCRIBE_KSQLDB_CONNECTORS,
    KSQLDB_CONNECTOR_PERMISSIONS.DELETE_KSQLDB_CONNECTOR,
    KSQLDB_CONNECTOR_PERMISSIONS.CREATE_KSQLDB_CONNECTOR,
] as const;

const KSQLDB_CONNECTOR_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable KsqlDb Connector Feature',
        permission:
            KSQLDB_CONNECTOR_PERMISSIONS.KSQLDB_CONNECTOR_FEATURE_ENABLED,
    },
    {
        label: 'Describe KsqlDb Connectors',
        permission: KSQLDB_CONNECTOR_PERMISSIONS.DESCRIBE_KSQLDB_CONNECTORS,
    },
    {
        label: 'Delete KsqlDb Connector',
        permission: KSQLDB_CONNECTOR_PERMISSIONS.DELETE_KSQLDB_CONNECTOR,
    },
    {
        label: 'Create KsqlDb Connector',
        permission: KSQLDB_CONNECTOR_PERMISSIONS.CREATE_KSQLDB_CONNECTOR,
    },
];

const KsqlDbConnectorPermissions = {
    KSQLDB_CONNECTOR_PERMISSIONS,
    KSQLDB_CONNECTOR_PERMISSIONS_LIST,
    KSQLDB_CONNECTOR_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { KsqlDbConnectorPermissions };
