import { PermissionLabel } from '..';

const KSQLDB_STREAM_PERMISSIONS = {
    KSQLDB_STREAM_FEATURE_ENABLED: 'KSQLDB_STREAM_FEATURE_ENABLED',
    DESCRIBE_KSQLDB_STREAMS: 'DESCRIBE_KSQLDB_STREAMS',
} as const;

const KSQLDB_STREAM_PERMISSIONS_LIST = [
    KSQLDB_STREAM_PERMISSIONS.KSQLDB_STREAM_FEATURE_ENABLED,
    KSQLDB_STREAM_PERMISSIONS.DESCRIBE_KSQLDB_STREAMS,
] as const;

const KSQLDB_STREAM_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable KsqlDb Stream Feature',
        permission: KSQLDB_STREAM_PERMISSIONS.KSQLDB_STREAM_FEATURE_ENABLED,
    },
    {
        label: 'Describe KsqlDb Streams',
        permission: KSQLDB_STREAM_PERMISSIONS.DESCRIBE_KSQLDB_STREAMS,
    },
];

const KsqlDbStreamPermissions = {
    KSQLDB_STREAM_PERMISSIONS,
    KSQLDB_STREAM_PERMISSIONS_LIST,
    KSQLDB_STREAM_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { KsqlDbStreamPermissions };
