import { PermissionLabel } from '..';

const KSQLDB_EDITOR_PERMISSIONS = {
    KSQLDB_EDITOR_FEATURE_ENABLED: 'KSQLDB_EDITOR_FEATURE_ENABLED',
    KSQLDB_EDITOR_EXECUTE_QUERY: 'KSQLDB_EDITOR_EXECUTE_QUERY',
    KSQLDB_EDITOR_STREAM_QUERY: 'KSQLDB_EDITOR_STREAM_QUERY',
    KSQLDB_EDITOR_EXECUTE_STATEMENT: 'KSQLDB_EDITOR_EXECUTE_STATEMENT',
} as const;

const KSQLDB_EDITOR_PERMISSIONS_LIST = [
    KSQLDB_EDITOR_PERMISSIONS.KSQLDB_EDITOR_FEATURE_ENABLED,
    KSQLDB_EDITOR_PERMISSIONS.KSQLDB_EDITOR_EXECUTE_QUERY,
    KSQLDB_EDITOR_PERMISSIONS.KSQLDB_EDITOR_STREAM_QUERY,
    KSQLDB_EDITOR_PERMISSIONS.KSQLDB_EDITOR_EXECUTE_STATEMENT,
] as const;

const KSQLDB_EDITOR_PERMISSIONS_LABELS_BY_PERMISSION: PermissionLabel[] = [
    {
        label: 'Enable KsqlDb Editor Feature',
        permission: KSQLDB_EDITOR_PERMISSIONS.KSQLDB_EDITOR_FEATURE_ENABLED,
    },
    {
        label: 'KsqlDb Editor Execute Query',
        permission: KSQLDB_EDITOR_PERMISSIONS.KSQLDB_EDITOR_EXECUTE_QUERY,
    },
    {
        label: 'KsqlDb Editor Stream Query',
        permission: KSQLDB_EDITOR_PERMISSIONS.KSQLDB_EDITOR_STREAM_QUERY,
    },
    {
        label: 'KsqlDb Editor Execute Statement',
        permission: KSQLDB_EDITOR_PERMISSIONS.KSQLDB_EDITOR_EXECUTE_STATEMENT,
    },
];

const KsqlDbEditorPermissions = {
    KSQLDB_EDITOR_PERMISSIONS,
    KSQLDB_EDITOR_PERMISSIONS_LIST,
    KSQLDB_EDITOR_PERMISSIONS_LABELS_BY_PERMISSION,
};

export { KsqlDbEditorPermissions };
