import { Text, Code, Anchor } from '@mantine/core';
import { KafkaConfiguration } from '../..';

const configuration: KafkaConfiguration = {
    name: 'compression.type',
    displayedName: 'compression.type',
    errorMessage: 'Please enter a valid value',
    documentation: (
        <Text size="md">
            The compression type for all data generated by the producer. The
            default is none (i.e. no compression). Valid values are{' '}
            <Code>none</Code>, <Code>gzip</Code>, <Code>snappy</Code>,{' '}
            <Code>lz4</Code>, or <Code>zstd</Code>. Compression is of full
            batches of data, so the efficacy of batching will also impact the
            compression ratio (more batching means better compression).
        </Text>
    ),
    importance: 'HIGH',
    isSelectable: true,
    required: false,
    type: 'STRING',
    documentationProps: (
        <Text className="pt-4" size="xs" color="dimmed">
            Props to Apache Kafka® for this amazing documentation,{' '}
            <Anchor
                size="xs"
                href={`https://kafka.apache.org/documentation/#producerconfigs_compression.type`}
                target="_blank"
            >
                learn more here
            </Anchor>
        </Text>
    ),
    default: 'none',
    options: [
        {
            label: 'none',
            value: 'none',
        },
        {
            label: 'gzip',
            value: 'gzip',
        },
        {
            label: 'snappy',
            value: 'snappy',
        },
        {
            label: 'lz4',
            value: 'lz4',
        },
        {
            label: 'zstd',
            value: 'zstd',
        },
    ],
    validValues: '[none, gzip, snappy, lz4, zstd]',
    displayedDefault: 'none',
    validate: target => {
        if (
            target === 'none' ||
            target === 'gzip' ||
            target === 'snappy' ||
            target === 'lz4' ||
            target === 'zstd'
        ) {
            return true;
        }
        return false;
    },
    disabledForever: false,
    numericUnit: undefined,
    proTip: undefined,
};

export default configuration;
