openapi: 3.0.0
info:
  description: Broker Api Documentation
  version: 0.1.0
  title: Broker Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: Broker
servers:
  - url: http://localhost:8080

paths:
  # Broker
  /v1/admin/brokers:
      get:
        tags:
            - Broker
        summary: Get Brokers
        operationId: getBrokers
        responses:
            200:
              description: OK

components:
  schemas:
    # Requests


    # Responses


    # Common

    CommonMap:
      type: object
      additionalProperties:
        type: object
    NotBlankString:
      type: string
      pattern: ^(?!\s*$).+
